using DeCloud.NodeAgent.Core.Interfaces;
using DeCloud.NodeAgent.Core.Interfaces.Qmp;
using Microsoft.Extensions.Logging;
using System.Text.Json;

namespace DeCloud.NodeAgent.Infrastructure.Services.Resilience;

/// <summary>
/// IQmpClient implementation via 'virsh qemu-monitor-command'.
/// Consistent with the existing virsh pattern used in VmReadinessMonitor
/// and EphemeralSshKeyService — no raw Unix socket management required.
/// </summary>
public class QmpClient : IQmpClient
{
    private readonly ICommandExecutor _executor;
    private readonly ILogger<QmpClient> _logger;

    public QmpClient(ICommandExecutor executor, ILogger<QmpClient> logger)
    {
        _executor = executor;
        _logger = logger;
    }

    public async Task<JsonElement> SendAsync(
        string vmId, string execute, object? arguments = null, CancellationToken ct = default)
    {
        var json = arguments == null
            ? $"{{\"execute\":\"{execute}\"}}"
            : $"{{\"execute\":\"{execute}\",\"arguments\":{JsonSerializer.Serialize(arguments)}}}";

        var escaped = json.Replace("\\", "\\\\").Replace("\"", "\\\"");
        var args = $"qemu-monitor-command {vmId} --pretty \"{escaped}\"";

        var result = await _executor.ExecuteAsync("virsh", args, TimeSpan.FromSeconds(10), ct);
        if (!result.Success)
            throw new InvalidOperationException(
                $"QMP {execute} failed for VM {vmId}: {result.StandardError}");

        using var doc = JsonDocument.Parse(result.StandardOutput.Trim());
        // virsh --pretty wraps the QMP response in {"return": ...}
        // Detect QMP-level error and surface as exception so callers can handle it.
        if (doc.RootElement.TryGetProperty("error", out var err))
        {
            var desc = err.TryGetProperty("desc", out var d) ? d.GetString() : "unknown";
            throw new InvalidOperationException(
                $"QMP {execute} error for VM {vmId}: {desc}");
        }
        if (doc.RootElement.TryGetProperty("return", out var ret))
            return ret.Clone();

        return doc.RootElement.Clone();
    }

    public async Task<string?> GetPrimaryDriveNodeAsync(string vmId, CancellationToken ct = default)
    {
        try
        {
            var ret = await SendAsync(vmId, "query-block", ct: ct);
            // Return the top-level device name (e.g. "drive-virtio-disk0") — this is
            // what blockdev-snapshot-sync's "device" argument expects. The internal
            // block node-name (inserted.node-name, e.g. "libvirt-2-format") is the
            // layer identifier used by newer QEMU node-based commands; blockdev-snapshot-sync
            // on this QEMU version uses the device name.
            foreach (var dev in ret.EnumerateArray())
            {
                if (dev.TryGetProperty("inserted", out _) &&
                    dev.TryGetProperty("device", out var deviceName))
                {
                    var name = deviceName.GetString();
                    if (!string.IsNullOrEmpty(name))
                        return name;
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "query-block failed for VM {VmId}", vmId);
        }
        return null;
    }

    public async Task<string> CreateSnapshotAsync(
        string vmId, string driveNode, string snapshotPath, CancellationToken ct = default)
    {
        // Phase J: blockdev-snapshot-sync atomically redirects the VM's write
        // path to a new qcow2 at snapshotPath, making the current disk immutable
        // at this exact point in time.
        //
        // Why this is coherent and drive-backup is not:
        //   drive-backup installs a COW snapshot point at job creation but then
        //   reads clusters sequentially over tens of seconds, unfrozen. Clusters
        //   are individually correct at T=0 but coupled ext4 metadata structures
        //   (journal, inode bitmap, inode table) are read at different wall-clock
        //   moments, producing temporal incoherence. Observed on msi-1867:
        //   journal transactions 9331 and 9332 absent from capture, dozens of
        //   directory entries pointing to "deleted/unused" inodes, VM unbootable.
        //
        //   blockdev-snapshot-sync performs no data movement. The snapshot IS the
        //   original disk file, frozen at the moment of the QMP call. The guest
        //   is frozen for one QMP round-trip; no writes can occur; every byte in
        //   the original file is at the same filesystem transaction boundary.
        //
        // Caller must hold guest-fsfreeze across this call.
        // snapshotPath must be pre-created and AppArmor-granted before this call.
        //
        // The return value is the QEMU block node name of the new live overlay
        // (auto-generated by QEMU). Pass it to DeleteSnapshotNodeAsync after
        // lazysync completes to detach the backing file relationship.
        // node-name for the new overlay — must be unique, non-empty, and
        // short enough to fit QEMU's 31-char node-name limit.
        var newNodeName = $"ls-ov-{vmId[..8]}";

        var ret = await SendAsync(vmId, "blockdev-snapshot-sync", new Dictionary<string, object>
        {
            ["device"] = driveNode,         // top-level device name from query-block
            ["snapshot-file"] = snapshotPath,
            ["snapshot-node-name"] = newNodeName,
            ["format"] = "qcow2",
            ["mode"] = "existing",          // file is pre-created by NodeAgent
        }, ct);
        // QEMU returns the new overlay's node-name in the response.
        // If absent (older QEMU), we derive it by convention: QEMU names it
        // "#block<N>" internally but exposes it in query-block. Query for it.
        if (ret.TryGetProperty("node-name", out var nodeName))
        {
            var name = nodeName.GetString();
            if (!string.IsNullOrEmpty(name))
            {
                _logger.LogDebug(
                    "VM {VmId}: snapshot created, new overlay node={Node}", vmId, name);
                return name;
            }
        }

        // Fallback: find the new node by querying block devices and matching
        // the snapshot file path as the backing file of the topmost node.
        var blocks = await SendAsync(vmId, "query-block", ct: ct);
        foreach (var dev in blocks.EnumerateArray())
        {
            if (!dev.TryGetProperty("inserted", out var ins)) continue;
            if (!ins.TryGetProperty("backing_file", out var bf)) continue;
            if (bf.GetString() == snapshotPath && ins.TryGetProperty("node-name", out var nn))
            {
                var name = nn.GetString() ?? string.Empty;
                _logger.LogDebug(
                    "VM {VmId}: snapshot created (fallback query), new overlay node={Node}",
                    vmId, name);
                return name;
            }
        }

        throw new InvalidOperationException(
            $"blockdev-snapshot-sync succeeded for VM {vmId} but new overlay node-name " +
            $"could not be determined. Check QEMU version supports node-name in response.");
    }

    public async Task DeleteSnapshotNodeAsync(
        string vmId, string newOverlayNode, string snapshotPath, CancellationToken ct = default)
    {
        // Phase J: detach the snapshot backing file from the live overlay.
        //
        // The snapshot (original disk.qcow2) is now the backing file of newOverlayNode
        // (the live overlay receiving guest writes). To free it:
        //   1. blockdev-snapshot-delete removes the backing file relationship,
        //      merging the snapshot's content into the overlay and making the
        //      overlay self-contained.
        //   2. Delete the snapshot file from disk.
        //
        // blockdev-snapshot-delete is the symmetric inverse of blockdev-snapshot-sync.
        // It commits the backing file content into the overlay — equivalent to
        // qemu-img commit but live, without stopping the VM.
        //
        // Non-fatal: if the QMP command fails (e.g. node already detached),
        // log at Warning and proceed to file deletion. The worst outcome of
        // leaving a detached backing file is a dangling file on disk — the
        // crash-recovery path in LibvirtVmManager handles it at next startup.
        try
        {
            await SendAsync(vmId, "blockdev-snapshot-delete", new Dictionary<string, object>
            {
                ["node"] = newOverlayNode,
                ["overlay"] = newOverlayNode,
            }, ct);
            _logger.LogDebug(
                "VM {VmId}: snapshot node {Node} detached", vmId, newOverlayNode);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "VM {VmId}: blockdev-snapshot-delete failed for node {Node} — " +
                "proceeding to file deletion; crash-recovery will handle any orphan",
                vmId, newOverlayNode);
        }

        if (File.Exists(snapshotPath))
        {
            try { File.Delete(snapshotPath); }
            catch (Exception ex)
            {
                _logger.LogWarning(ex,
                    "VM {VmId}: failed to delete snapshot file {Path}", vmId, snapshotPath);
            }
        }
    }

    public async Task GrantScratchAppArmorAsync(string vmId, string path, CancellationToken ct = default)
    {
        // libvirt generates /etc/apparmor.d/libvirt/libvirt-<uuid>.files at VM start
        // and updates it on disk attach/detach. We write the same rule format directly,
        // then reload the profile — no PCI slot required, scope remains per-VM.
        var filesProfile = $"/etc/apparmor.d/libvirt/libvirt-{vmId}.files";
        if (!File.Exists(filesProfile))
        {
            _logger.LogDebug("VM {VmId}: AppArmor .files profile not found — skipping grant", vmId);
            return; // AppArmor not active on this host
        }

        await File.AppendAllTextAsync(filesProfile, $"  \"{path}\" rw,\n", ct);

        var result = await _executor.ExecuteAsync(
            "apparmor_parser",
            $"-r /etc/apparmor.d/libvirt/libvirt-{vmId}",
            TimeSpan.FromSeconds(10), ct);

        if (!result.Success)
            throw new InvalidOperationException(
                $"apparmor_parser reload failed for VM {vmId}: {result.StandardError}");

        _logger.LogDebug("VM {VmId}: AppArmor scratch access granted ({Path})", vmId, path);
    }

    public async Task RevokeScratchAppArmorAsync(string vmId, string path, CancellationToken ct = default)
    {
        var filesProfile = $"/etc/apparmor.d/libvirt/libvirt-{vmId}.files";
        if (!File.Exists(filesProfile)) return;

        var rule = $"  \"{path}\" rw,";
        var lines = await File.ReadAllLinesAsync(filesProfile, ct);
        var filtered = lines.Where(l => l.TrimEnd() != rule).ToArray();

        if (filtered.Length == lines.Length) return; // rule already absent — nothing to do

        await File.WriteAllLinesAsync(filesProfile, filtered, ct);

        var result = await _executor.ExecuteAsync(
            "apparmor_parser",
            $"-r /etc/apparmor.d/libvirt/libvirt-{vmId}",
            TimeSpan.FromSeconds(10), ct);

        if (!result.Success)
            _logger.LogWarning("VM {VmId}: apparmor_parser reload failed during revoke: {Err}",
                vmId, result.StandardError);
        else
            _logger.LogDebug("VM {VmId}: AppArmor scratch access revoked ({Path})", vmId, path);
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Phase D+2: guest agent commands (qemu-agent-command, not qemu-monitor-command)
    // ═══════════════════════════════════════════════════════════════════════

    /// <summary>
    /// Send a raw guest-agent command. Same escaping pattern as SendAsync
    /// but targets qemu-agent-command, which goes to the guest agent socket
    /// (vsock or virtio-serial) rather than the QMP monitor socket.
    /// </summary>
    private async Task<JsonElement> SendAgentAsync(
        string vmId, string execute, object? arguments = null,
        TimeSpan? timeout = null, CancellationToken ct = default)
    {
        var json = arguments == null
            ? $"{{\"execute\":\"{execute}\"}}"
            : $"{{\"execute\":\"{execute}\",\"arguments\":{JsonSerializer.Serialize(arguments)}}}";

        var escaped = json.Replace("\\", "\\\\").Replace("\"", "\\\"");
        var args = $"qemu-agent-command {vmId} \"{escaped}\"";

        var result = await _executor.ExecuteAsync(
            "virsh", args, timeout ?? TimeSpan.FromSeconds(10), ct);

        if (!result.Success)
            throw new InvalidOperationException(
                $"Guest agent {execute} failed for VM {vmId}: {result.StandardError}");

        using var doc = JsonDocument.Parse(result.StandardOutput.Trim());
        if (doc.RootElement.TryGetProperty("error", out var err))
        {
            var desc = err.TryGetProperty("desc", out var d) ? d.GetString() : "unknown";
            throw new InvalidOperationException(
                $"Guest agent {execute} error for VM {vmId}: {desc}");
        }
        if (doc.RootElement.TryGetProperty("return", out var ret))
            return ret.Clone();

        return doc.RootElement.Clone();
    }

    public async Task<int> FsFreezeAsync(string vmId, CancellationToken ct = default)
    {
        // Generous timeout: freeze drives a sync inside the guest, which on a
        // VM under write pressure can take many seconds. 30s is the floor used
        // by libvirt's own virsh domfsfreeze when no override is given.
        var ret = await SendAgentAsync(
            vmId, "guest-fsfreeze-freeze",
            timeout: TimeSpan.FromSeconds(30), ct: ct);

        var count = ret.ValueKind == JsonValueKind.Number ? ret.GetInt32() : 0;
        _logger.LogDebug("VM {VmId}: froze {Count} filesystem(s)", vmId, count);
        return count;
    }

    public async Task<int> FsThawAsync(string vmId, CancellationToken ct = default)
    {
        var ret = await SendAgentAsync(
            vmId, "guest-fsfreeze-thaw",
            timeout: TimeSpan.FromSeconds(30), ct: ct);

        var count = ret.ValueKind == JsonValueKind.Number ? ret.GetInt32() : 0;
        _logger.LogDebug("VM {VmId}: thawed {Count} filesystem(s)", vmId, count);
        return count;
    }

    public async Task<bool> GuestAgentPingAsync(string vmId, CancellationToken ct = default)
    {
        try
        {
            await SendAgentAsync(
                vmId, "guest-ping",
                timeout: TimeSpan.FromSeconds(2), ct: ct);
            return true;
        }
        catch
        {
            return false;
        }
    }
}