#cloud-config

# DeCloud Relay VM Bootstrap Configuration
# This VM acts as a WireGuard relay and reverse proxy for CGNAT nodes
# Provides: WireGuard server, Nginx reverse proxy, Management API, Firewall

hostname: __HOSTNAME__

manage_etc_hosts: true

# =====================================================
# SYSTEM UPDATES
# =====================================================
package_update: true
package_upgrade: true

# =====================================================
# REQUIRED PACKAGES
# =====================================================
packages:
  - wireguard
  - wireguard-tools
  - nginx
  - iptables
  - curl
  - wget
  - net-tools
  - htop
  - fail2ban
  - ufw
  - python3
  - python3-pip
  - qemu-guest-agent

# =====================================================
# CRITICAL: Regenerate machine-id
# =====================================================
bootcmd:
  - rm -f /etc/machine-id /var/lib/dbus/machine-id
  - systemd-machine-id-setup

# =====================================================
# USER CONFIGURATION
# Relay VMs use ubuntu user (no root login for security)
# =====================================================
disable_root: true

users:
  - name: ubuntu
    lock_passwd: true
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash

ssh_pwauth: false

# =====================================================
# FILES CONFIGURATION
# =====================================================
write_files:
  # WireGuard configuration template
  - path: /etc/wireguard/wg0.conf
    permissions: '0600'
    content: |
      [Interface]
      PrivateKey = __WIREGUARD_PRIVATE_KEY__
      Address = 10.20.0.1/16
      ListenPort = 51820
      PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      
      # CGNAT node peers will be added dynamically via API
      # Use: POST /api/relay/add-peer with {public_key, tunnel_ip}
  
  # Nginx reverse proxy configuration
  - path: /etc/nginx/sites-available/relay-proxy
    permissions: '0644'
    content: |
      # Relay proxy configuration for CGNAT nodes
      upstream cgnat_nodes {
          least_conn;
          # CGNAT node backends added dynamically
          # Use: POST /api/relay/add-backend with {node_id, backend_ip, backend_port}
      }
      
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          
          server_name _;
          
          # Health check endpoint
          location /health {
              access_log off;
              return 200 "OK\n";
              add_header Content-Type text/plain;
          }
          
          # Relay status page
          location /relay/status {
              default_type application/json;
              return 200 '{"relay_id":"__VM_ID__","status":"online","region":"__RELAY_REGION__","capacity":__RELAY_CAPACITY__}';
          }
          
          # Proxy to CGNAT nodes
          location / {
              proxy_pass http://cgnat_nodes;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              
              # WebSocket support
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              
              # Timeouts
              proxy_connect_timeout 60s;
              proxy_send_timeout 60s;
              proxy_read_timeout 60s;
          }
      }
  
  # Relay management API
  - path: /opt/decloud-relay/relay-api.py
    permissions: '0755'
    content: |
      #!/usr/bin/env python3
      """
      DeCloud Relay Management API
      Provides endpoints for dynamic peer and backend management
      """
      from http.server import HTTPServer, BaseHTTPRequestHandler
      import json
      import subprocess
      import logging
      
      logging.basicConfig(level=logging.INFO)
      logger = logging.getLogger('relay-api')
      
      class RelayAPI(BaseHTTPRequestHandler):
          def log_message(self, format, *args):
              logger.info("%s - - [%s] %s" % (
                  self.client_address[0],
                  self.log_date_time_string(),
                  format % args))
          
          def do_GET(self):
              if self.path == '/api/relay/status':
                  self.send_response(200)
                  self.send_header('Content-Type', 'application/json')
                  self.end_headers()
                  
                  # Get WireGuard status
                  try:
                      result = subprocess.run(['wg', 'show', 'wg0'], 
                                            capture_output=True, text=True)
                      peer_count = result.stdout.count('peer:')
                  except:
                      peer_count = 0
                  
                  status = {
                      'relay_id': '__VM_ID__',
                      'status': 'online',
                      'region': '__RELAY_REGION__',
                      'capacity': __RELAY_CAPACITY__,
                      'connected_peers': peer_count
                  }
                  self.wfile.write(json.dumps(status).encode())
              else:
                  self.send_error(404)
          
          def do_POST(self):
              if self.path == '/api/relay/add-peer':
                  self.add_wireguard_peer()
              elif self.path == '/api/relay/remove-peer':
                  self.remove_wireguard_peer()
              elif self.path == '/api/relay/add-backend':
                  self.add_nginx_backend()
              else:
                  self.send_error(404)
          
          def add_wireguard_peer(self):
              try:
                  content_length = int(self.headers['Content-Length'])
                  post_data = self.rfile.read(content_length)
                  peer = json.loads(post_data)
                  
                  # Validate required fields
                  if 'public_key' not in peer or 'tunnel_ip' not in peer:
                      self.send_error(400, 'Missing public_key or tunnel_ip')
                      return
                  
                  # Add WireGuard peer
                  cmd = [
                      'wg', 'set', 'wg0',
                      'peer', peer['public_key'],
                      'allowed-ips', peer['tunnel_ip'] + '/32'
                  ]
                  
                  if 'endpoint' in peer:
                      cmd.extend(['endpoint', peer['endpoint']])
                  
                  result = subprocess.run(cmd, capture_output=True)
                  
                  if result.returncode == 0:
                      logger.info(f"Added WireGuard peer: {peer['public_key'][:12]}...")
                      
                      # Persist configuration
                      subprocess.run(['wg-quick', 'save', 'wg0'])
                      
                      self.send_response(200)
                      self.send_header('Content-Type', 'application/json')
                      self.end_headers()
                      self.wfile.write(json.dumps({
                          'status': 'success',
                          'message': 'Peer added successfully'
                      }).encode())
                  else:
                      logger.error(f"Failed to add peer: {result.stderr.decode()}")
                      self.send_error(500, result.stderr.decode())
              except Exception as e:
                  logger.exception("Error adding peer")
                  self.send_error(500, str(e))
          
          def remove_wireguard_peer(self):
              try:
                  content_length = int(self.headers['Content-Length'])
                  post_data = self.rfile.read(content_length)
                  peer = json.loads(post_data)
                  
                  if 'public_key' not in peer:
                      self.send_error(400, 'Missing public_key')
                      return
                  
                  cmd = ['wg', 'set', 'wg0', 'peer', peer['public_key'], 'remove']
                  result = subprocess.run(cmd, capture_output=True)
                  
                  if result.returncode == 0:
                      logger.info(f"Removed WireGuard peer: {peer['public_key'][:12]}...")
                      subprocess.run(['wg-quick', 'save', 'wg0'])
                      
                      self.send_response(200)
                      self.send_header('Content-Type', 'application/json')
                      self.end_headers()
                      self.wfile.write(json.dumps({
                          'status': 'success',
                          'message': 'Peer removed successfully'
                      }).encode())
                  else:
                      self.send_error(500, result.stderr.decode())
              except Exception as e:
                  logger.exception("Error removing peer")
                  self.send_error(500, str(e))
          
          def add_nginx_backend(self):
              try:
                  content_length = int(self.headers['Content-Length'])
                  post_data = self.rfile.read(content_length)
                  backend = json.loads(post_data)
                  
                  # TODO: Implement dynamic nginx backend management
                  # This requires nginx with ngx_http_api_module or dynamic reconfiguration
                  
                  logger.info(f"Backend registration request: {backend}")
                  
                  self.send_response(200)
                  self.send_header('Content-Type', 'application/json')
                  self.end_headers()
                  self.wfile.write(json.dumps({
                      'status': 'accepted',
                      'message': 'Backend registered (requires nginx reload)'
                  }).encode())
              except Exception as e:
                  logger.exception("Error adding backend")
                  self.send_error(500, str(e))
      
      if __name__ == '__main__':
          logger.info('Starting DeCloud Relay API on port 8080')
          server = HTTPServer(('0.0.0.0', 8080), RelayAPI)
          try:
              server.serve_forever()
          except KeyboardInterrupt:
              logger.info('Shutting down relay API')
              server.shutdown()
  
  # Relay API systemd service
  - path: /etc/systemd/system/decloud-relay-api.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud Relay Management API
      After=network.target wireguard@wg0.service
      
      [Service]
      Type=simple
      User=root
      ExecStart=/usr/bin/python3 /opt/decloud-relay/relay-api.py
      Restart=always
      RestartSec=10
      
      [Install]
      WantedBy=multi-user.target
  
  # DeCloud relay metadata
  - path: /etc/decloud/relay-info.json
    permissions: '0644'
    content: |
      {
        "relay_id": "__VM_ID__",
        "relay_name": "__VM_NAME__",
        "region": "__RELAY_REGION__",
        "max_capacity": __RELAY_CAPACITY__,
        "wireguard_endpoint": "__PUBLIC_IP__:51820",
        "wireguard_public_key": "__WIREGUARD_PUBLIC_KEY__",
        "created_at": "__TIMESTAMP__"
      }

# =====================================================
# RUNTIME COMMANDS
# =====================================================
runcmd:
  # Enable IP forwarding (required for relay functionality)
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf
  - sysctl -p
  
  # Configure firewall (UFW)
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp comment "SSH"
  - ufw allow 51820/udp comment "WireGuard"
  - ufw allow 80/tcp comment "HTTP Proxy"
  - ufw allow 8080/tcp comment "Relay API"
  - ufw --force enable
  
  # Enable and start QEMU guest agent
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  
  # Start WireGuard
  - systemctl enable wg-quick@wg0
  - systemctl start wg-quick@wg0
  
  # Configure and start Nginx
  - ln -sf /etc/nginx/sites-available/relay-proxy /etc/nginx/sites-enabled/
  - rm -f /etc/nginx/sites-enabled/default
  - nginx -t
  - systemctl enable nginx
  - systemctl restart nginx
  
  # Start relay management API
  - systemctl daemon-reload
  - systemctl enable decloud-relay-api
  - systemctl start decloud-relay-api
  
  # Configure fail2ban for SSH protection
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Create directory for relay API
  - mkdir -p /opt/decloud-relay
  - mkdir -p /etc/decloud
  
  # Log completion
  - echo "DeCloud relay VM bootstrap complete at $(date)" > /var/log/decloud-relay-bootstrap.log
  - echo "Relay ID: __VM_ID__" >> /var/log/decloud-relay-bootstrap.log
  - echo "Region: __RELAY_REGION__" >> /var/log/decloud-relay-bootstrap.log
  - echo "WireGuard Public Key: __WIREGUARD_PUBLIC_KEY__" >> /var/log/decloud-relay-bootstrap.log

final_message: "DeCloud Relay VM __VM_NAME__ is ready! WireGuard endpoint: __PUBLIC_IP__:51820"
