#cloud-config
# DeCloud DHT VM Cloud-Init Configuration
# Runs a libp2p Kademlia DHT node for peer discovery,
# key-value storage, and GossipSub event propagation.
# Version: 3.1 (Added dashboard server)

hostname: __HOSTNAME__
manage_etc_hosts: true

# Regenerate machine-id to prevent conflicts
bootcmd:
  - rm -f /etc/machine-id /var/lib/dbus/machine-id
  - systemd-machine-id-setup

# DHT nodes use dedicated dht user (not root)
disable_root: true

users:
  - name: dht
    groups: [sudo]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    lock_passwd: true

# SSH key authentication for dht user
__SSH_AUTHORIZED_KEYS_BLOCK__

ssh_pwauth: false

# =====================================================
# SYSTEM PACKAGES
# =====================================================
packages:
  - qemu-guest-agent
  - curl
  - jq
  - net-tools
  - openssl
  - iptables
  - python3

# =====================================================
# SYSTEM CONFIGURATION
# =====================================================
write_files:
  # DHT binary (gzip+base64-encoded Go binary, decoded by cloud-init at boot)
  - path: /usr/local/bin/dht-node
    permissions: '0755'
    encoding: gz+b64
    content: __DHT_NODE_BINARY_GZ_BASE64__

  # DHT environment file (read by systemd EnvironmentFile)
  - path: /etc/decloud-dht/dht.env
    permissions: '0644'
    content: |
      DHT_LISTEN_PORT=__DHT_LISTEN_PORT__
      DHT_API_PORT=__DHT_API_PORT__
      DHT_ADVERTISE_IP=__DHT_ADVERTISE_IP__
      DHT_BOOTSTRAP_PEERS=__DHT_BOOTSTRAP_PEERS__
      DHT_DATA_DIR=/var/lib/decloud-dht
      DECLOUD_NODE_ID=__NODE_ID__
      DECLOUD_REGION=__DHT_REGION__

  # DHT metadata
  - path: /etc/decloud/dht-metadata.json
    permissions: '0644'
    content: |
      {
        "node_id": "__NODE_ID__",
        "vm_id": "__VM_ID__",
        "vm_name": "__VM_NAME__",
        "region": "__DHT_REGION__",
        "listen_port": __DHT_LISTEN_PORT__,
        "api_port": __DHT_API_PORT__,
        "advertise_ip": "__DHT_ADVERTISE_IP__",
        "created_at": "__TIMESTAMP__",
        "version": "3.1"
      }

  # DHT systemd service (runs binary directly, no Docker)
  - path: /etc/systemd/system/decloud-dht.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Node (libp2p Kademlia)
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=simple
      User=dht
      EnvironmentFile=/etc/decloud-dht/dht.env
      ExecStart=/usr/local/bin/dht-node
      Restart=always
      RestartSec=5

      # Hardening
      ProtectSystem=strict
      ReadWritePaths=/var/lib/decloud-dht
      ProtectHome=true
      NoNewPrivileges=true

      [Install]
      WantedBy=multi-user.target

  # Dashboard server (Python — serves UI and proxies to DHT API)
  - path: /opt/decloud-dht/dht-dashboard.py
    permissions: '0755'
    content: |
      __DHT_DASHBOARD_PY__

  # Dashboard systemd service
  - path: /etc/systemd/system/decloud-dht-dashboard.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Dashboard Server
      After=decloud-dht.service
      Wants=decloud-dht.service

      [Service]
      Type=simple
      EnvironmentFile=/etc/decloud-dht/dht.env
      ExecStart=/usr/bin/python3 /opt/decloud-dht/dht-dashboard.py
      Restart=always
      RestartSec=5
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target

  # DHT ready callback service (mirrors relay's decloud-relay-nat-callback pattern)
  - path: /etc/systemd/system/decloud-dht-callback.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Ready Callback
      After=decloud-dht.service network-online.target
      Wants=decloud-dht.service network-online.target

      [Service]
      Type=oneshot
      ExecStartPre=/bin/bash -c 'if [ -f /var/lib/decloud-dht/callback-complete ]; then exit 0; fi'
      ExecStart=/usr/local/bin/dht-notify-ready.sh
      RemainAfterExit=yes
      StandardOutput=journal
      StandardError=journal
      Restart=on-failure
      RestartSec=10s
      StartLimitBurst=5
      TimeoutStartSec=180s

      [Install]
      WantedBy=multi-user.target

  # Health check script (loaded from external template)
  - path: /usr/local/bin/dht-health-check.sh
    permissions: '0755'
    content: |
      __DHT_HEALTH_CHECK__

  # Ready callback script (loaded from external template)
  - path: /usr/local/bin/dht-notify-ready.sh
    permissions: '0755'
    content: |
      __DHT_NOTIFY_READY__

  # Dashboard static files (loaded from external templates)
  - path: /opt/decloud-dht/static/dashboard.html
    permissions: '0644'
    content: |
      __DHT_DASHBOARD_HTML__

  - path: /opt/decloud-dht/static/dashboard.css
    permissions: '0644'
    content: |
      __DHT_DASHBOARD_CSS__

  - path: /opt/decloud-dht/static/dashboard.js
    permissions: '0644'
    content: |
      __DHT_DASHBOARD_JS__

# =====================================================
# RUNTIME COMMANDS
# =====================================================
runcmd:
  # Enable and start QEMU guest agent (static unit - systemctl enable fails silently)
  - ln -sf /lib/systemd/system/qemu-guest-agent.service /etc/systemd/system/multi-user.target.wants/qemu-guest-agent.service
  - systemctl start qemu-guest-agent

  # Create directories
  - mkdir -p /etc/decloud-dht
  - mkdir -p /etc/decloud
  - mkdir -p /var/lib/decloud-dht
  - mkdir -p /opt/decloud-dht/static
  - chown -R dht:dht /etc/decloud-dht
  - chown -R dht:dht /var/lib/decloud-dht
  - chown -R dht:dht /opt/decloud-dht

  # DHT binary is written directly to /usr/local/bin/dht-node by write_files
  # with gz+b64 encoding (cloud-init handles decompression and decoding)

  # Redirect port 80 → dashboard server (8080) so ingress/subdomain access works
  - iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
  - iptables -t nat -A OUTPUT -p tcp -o lo --dport 80 -j REDIRECT --to-port 8080

  # Start DHT service
  - systemctl daemon-reload
  - systemctl enable decloud-dht
  - systemctl start decloud-dht

  # Start dashboard server (after DHT is up)
  - systemctl enable decloud-dht-dashboard
  - systemctl start decloud-dht-dashboard

  # Start ready callback service
  - systemctl enable decloud-dht-callback
  - systemctl start decloud-dht-callback

  # Log completion
  - 'echo "DeCloud DHT node __VM_ID__ bootstrap complete at $(date)" >> /var/log/dht-bootstrap.log'
  - 'echo "Region: __DHT_REGION__" >> /var/log/dht-bootstrap.log'
  - 'echo "Advertise IP: __DHT_ADVERTISE_IP__" >> /var/log/dht-bootstrap.log'

final_message: "DeCloud DHT Node __VM_NAME__ is ready!"
