#cloud-config
# DeCloud DHT VM Cloud-Init Configuration
# Runs a libp2p Kademlia DHT node for peer discovery,
# key-value storage, and GossipSub event propagation.
# Version: 5.0 (direct orchestrator bootstrap polling)

hostname: __HOSTNAME__
manage_etc_hosts: true

# Regenerate machine-id to prevent conflicts
bootcmd:
  - rm -f /etc/machine-id /var/lib/dbus/machine-id
  - systemd-machine-id-setup

# DHT nodes use dedicated dht user (not root)
disable_root: true

users:
  - name: dht
    groups: [sudo]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    lock_passwd: true

# SSH key authentication for dht user
__SSH_AUTHORIZED_KEYS_BLOCK__

ssh_pwauth: false

# =====================================================
# SYSTEM PACKAGES
# =====================================================
packages:
  - qemu-guest-agent
  - curl
  - jq
  - net-tools
  - openssl
  - nginx
  - wireguard
  - wireguard-tools
  - python3
  - wireguard
  - wireguard-tools

# =====================================================
# SYSTEM CONFIGURATION
# =====================================================
write_files:
  # DHT binary (gzip+base64-encoded Go binary, decoded by cloud-init at boot)
  - path: /usr/local/bin/dht-node
    permissions: '0755'
    encoding: gz+b64
    content: __DHT_NODE_BINARY_GZ_BASE64__

  # DHT environment file (read by systemd EnvironmentFile)
  # DHT_ADVERTISE_IP is set dynamically by wg-mesh-enroll.sh after WireGuard is up
  - path: /etc/decloud-dht/dht.env
    permissions: '0644'
    content: |
      DHT_LISTEN_PORT=__DHT_LISTEN_PORT__
      DHT_API_PORT=__DHT_API_PORT__
      DHT_ADVERTISE_IP=__WG_TUNNEL_IP__
      DHT_BOOTSTRAP_PEERS=__DHT_BOOTSTRAP_PEERS__
      DHT_DATA_DIR=/var/lib/decloud-dht
      DECLOUD_NODE_ID=__NODE_ID__
      DECLOUD_REGION=__DHT_REGION__

  # WireGuard mesh enrollment environment variables
  - path: /etc/decloud/wg-mesh.env
    permissions: '0600'
    content: |
      WG_RELAY_ENDPOINT=__WG_RELAY_ENDPOINT__
      WG_RELAY_PUBKEY=__WG_RELAY_PUBKEY__
      WG_TUNNEL_IP=__WG_TUNNEL_IP__
      WG_RELAY_API=__WG_RELAY_API__
      WG_INTERFACE=wg-mesh
      WG_DESCRIPTION=dht-__VM_ID__
      WG_PEER_TYPE=system-vm
      WG_PARENT_NODE_ID=__NODE_ID__

  # WireGuard mesh enrollment script (building block)
  - path: /usr/local/bin/wg-mesh-enroll.sh
    permissions: '0755'
    content: |
      __WG_MESH_ENROLL__

  # DHT metadata
  - path: /etc/decloud/dht-metadata.json
    permissions: '0644'
    content: |
      {
        "node_id": "__NODE_ID__",
        "vm_id": "__VM_ID__",
        "vm_name": "__VM_NAME__",
        "region": "__DHT_REGION__",
        "listen_port": __DHT_LISTEN_PORT__,
        "api_port": __DHT_API_PORT__,
        "advertise_ip": "__WG_TUNNEL_IP__",
        "wg_tunnel_ip": "__WG_TUNNEL_IP__",
        "created_at": "__TIMESTAMP__",
        "version": "4.0",
        "connectivity": "wireguard-mesh"
      }

  # WireGuard mesh enrollment script (reusable building block)
  - path: /usr/local/bin/wg-mesh-enroll.sh
    permissions: '0755'
    content: |
      __WG_MESH_ENROLL__

  # WireGuard mesh environment (consumed by enrollment script)
  - path: /etc/decloud/wg-mesh.env
    permissions: '0600'
    content: |
      WG_RELAY_ENDPOINT=__WG_RELAY_ENDPOINT__
      WG_RELAY_PUBKEY=__WG_RELAY_PUBKEY__
      WG_TUNNEL_IP=__WG_TUNNEL_IP__
      WG_RELAY_API=__WG_RELAY_API__
      WG_INTERFACE=wg-mesh
      WG_DESCRIPTION=DHT-__VM_ID__
      WG_PEER_TYPE=system-vm
      WG_PARENT_NODE_ID=__NODE_ID__

  # Nginx reverse proxy — port 80 → dashboard (8080) and DHT API
  - path: /etc/nginx/sites-available/dht-proxy
    permissions: '0644'
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;

          server_name _;

          # Nginx health check (fast, no proxy)
          location = /nginx-health {
              return 200 "OK\n";
              add_header Content-Type text/plain;
          }

          # Static dashboard assets → Python dashboard server
          location /static/ {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_connect_timeout 5s;
              proxy_read_timeout 10s;
          }

          # DHT API endpoints → Python dashboard server (proxies to Go binary)
          location /health {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_connect_timeout 5s;
              proxy_read_timeout 10s;
          }

          location /peers {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_connect_timeout 5s;
              proxy_read_timeout 10s;
          }

          # /connect and /publish are internal-only (token-protected,
          # localhost-bound on the Go binary). Not exposed via nginx.

          # Dashboard root → Python dashboard server
          location = / {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_connect_timeout 5s;
              proxy_read_timeout 10s;
          }
      }

  # DHT systemd service — starts AFTER WireGuard mesh is up
  - path: /etc/systemd/system/decloud-dht.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Node (libp2p Kademlia)
      After=network-online.target wg-quick@wg-mesh.service
      Wants=network-online.target wg-quick@wg-mesh.service

      [Service]
      Type=simple
      User=dht
      EnvironmentFile=/etc/decloud-dht/dht.env
      ExecStart=/usr/local/bin/dht-node
      Restart=always
      RestartSec=5

      # Hardening
      ProtectSystem=strict
      ReadWritePaths=/var/lib/decloud-dht
      ProtectHome=true
      NoNewPrivileges=true

      [Install]
      WantedBy=multi-user.target

  # Dashboard server (Python — serves UI and proxies API to Go binary)
  - path: /opt/decloud-dht/dht-dashboard.py
    permissions: '0755'
    content: |
      __DHT_DASHBOARD_PY__

  # Dashboard systemd service
  - path: /etc/systemd/system/decloud-dht-dashboard.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Dashboard Server
      After=decloud-dht.service nginx.service
      Wants=decloud-dht.service nginx.service

      [Service]
      Type=simple
      EnvironmentFile=/etc/decloud-dht/dht.env
      ExecStart=/usr/bin/python3 /opt/decloud-dht/dht-dashboard.py
      Restart=always
      RestartSec=5
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target

  # DHT ready callback service (mirrors relay's decloud-relay-nat-callback pattern)
  - path: /etc/systemd/system/decloud-dht-callback.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Ready Callback
      After=decloud-dht.service network-online.target
      Wants=decloud-dht.service network-online.target

      [Service]
      Type=oneshot
      ExecStartPre=/bin/bash -c 'if [ -f /var/lib/decloud-dht/callback-complete ]; then exit 0; fi'
      ExecStart=/usr/local/bin/dht-notify-ready.sh
      RemainAfterExit=yes
      StandardOutput=journal
      StandardError=journal
      Restart=on-failure
      RestartSec=10s
      StartLimitBurst=5
      TimeoutStartSec=180s

      [Install]
      WantedBy=multi-user.target

  # Bootstrap poll service — polls orchestrator for peers while isolated
  # Long-lived service (not oneshot like the callback above)
  - path: /etc/systemd/system/decloud-dht-bootstrap-poll.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud DHT Bootstrap Peer Polling
      After=decloud-dht.service network-online.target
      Wants=decloud-dht.service network-online.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/dht-bootstrap-poll.sh
      Restart=always
      RestartSec=15
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target

  # Health check script (loaded from external template)
  - path: /usr/local/bin/dht-health-check.sh
    permissions: '0755'
    content: |
      __DHT_HEALTH_CHECK__

  # Ready callback script (loaded from external template)
  # Kept as backup path — notifies NodeAgent of peerId for heartbeat reporting.
  # Primary peerId registration now happens via dht-bootstrap-poll → orchestrator.
  - path: /usr/local/bin/dht-notify-ready.sh
    permissions: '0755'
    content: |
      __DHT_NOTIFY_READY__

  # Bootstrap poll script (loaded from external template)
  # Polls orchestrator directly for bootstrap peers (relay callback pattern)
  - path: /usr/local/bin/dht-bootstrap-poll.sh
    permissions: '0755'
    content: |
      __DHT_BOOTSTRAP_POLL__

  # Dashboard static files (loaded from external templates)
  - path: /opt/decloud-dht/static/dashboard.html
    permissions: '0644'
    content: |
      __DHT_DASHBOARD_HTML__

  - path: /opt/decloud-dht/static/dashboard.css
    permissions: '0644'
    content: |
      __DHT_DASHBOARD_CSS__

  - path: /opt/decloud-dht/static/dashboard.js
    permissions: '0644'
    content: |
      __DHT_DASHBOARD_JS__

# =====================================================
# RUNTIME COMMANDS
# =====================================================
runcmd:
  # Enable and start QEMU guest agent (static unit - systemctl enable fails silently)
  - ln -sf /lib/systemd/system/qemu-guest-agent.service /etc/systemd/system/multi-user.target.wants/qemu-guest-agent.service
  - systemctl start qemu-guest-agent

  # WireGuard mesh enrollment — must happen before DHT starts
  # The enrollment script sources /etc/decloud/wg-mesh.env itself.
  # Skip gracefully if relay config is missing (no relay found at deploy time).
  - bash -c 'set -a && source /etc/decloud/wg-mesh.env && set +a && if [ -n "$WG_RELAY_ENDPOINT" ] && [ -n "$WG_RELAY_PUBKEY" ]; then /usr/local/bin/wg-mesh-enroll.sh; else echo "[wg-mesh] Skipping enrollment — no relay configured"; fi'

  # Configure and start Nginx
  - ln -sf /etc/nginx/sites-available/dht-proxy /etc/nginx/sites-enabled/
  - rm -f /etc/nginx/sites-enabled/default
  - nginx -t
  - systemctl enable nginx
  - systemctl restart nginx

  # Create directories
  - mkdir -p /etc/decloud-dht
  - mkdir -p /etc/decloud
  - mkdir -p /var/lib/decloud-dht
  - mkdir -p /opt/decloud-dht/static
  - chown -R dht:dht /etc/decloud-dht
  - chown -R dht:dht /var/lib/decloud-dht
  - chown -R dht:dht /opt/decloud-dht

  # =====================================================
  # WIREGUARD MESH ENROLLMENT (building block)
  # Joins the relay's WireGuard network so DHT nodes
  # can communicate directly — no port forwarding needed.
  # =====================================================
  - |
    set -a
    source /etc/decloud/wg-mesh.env
    set +a
    /usr/local/bin/wg-mesh-enroll.sh

  # DHT binary is written directly to /usr/local/bin/dht-node by write_files
  # with gz+b64 encoding (cloud-init handles decompression and decoding)

  # Start DHT service (after WireGuard mesh is up)
  - systemctl daemon-reload
  - systemctl enable decloud-dht
  - systemctl start decloud-dht

  # Start dashboard server (after DHT is up)
  - systemctl enable decloud-dht-dashboard
  - systemctl start decloud-dht-dashboard

  # Start ready callback service (backup — notifies NodeAgent)
  - systemctl enable decloud-dht-callback
  - systemctl start decloud-dht-callback

  # Start bootstrap poll service (primary — talks to orchestrator directly)
  - systemctl enable decloud-dht-bootstrap-poll
  - systemctl start decloud-dht-bootstrap-poll

  # Log completion
  - 'echo "DeCloud DHT node __VM_ID__ bootstrap complete at $(date)" >> /var/log/dht-bootstrap.log'
  - 'echo "Region: __DHT_REGION__" >> /var/log/dht-bootstrap.log'
  - 'echo "WireGuard tunnel IP: __WG_TUNNEL_IP__" >> /var/log/dht-bootstrap.log'

final_message: "DeCloud DHT Node __VM_NAME__ is ready!"
