#cloud-config

# DeCloud General VM Configuration
# For standard user VMs with full root access

hostname: __HOSTNAME__
manage_etc_hosts: true

# CRITICAL: Regenerate machine-id BEFORE networking starts
# Prevents DHCP IP address collisions when cloning from base image
bootcmd:
  - rm -f /etc/machine-id /var/lib/dbus/machine-id
  - systemd-machine-id-setup

# Root user configuration
# Single-tenant VMs get direct root access (similar to Hetzner, Vultr, Linode)
disable_root: false

# SSH public key authentication (placeholder will be replaced with actual block)
# Format: ssh_authorized_keys:\n  - ssh-rsa AAA...
# __SSH_AUTHORIZED_KEYS_BLOCK__

# Password authentication (placeholder will be replaced with actual block)
# Format: chpasswd:\n  list: |\n    root:password
__PASSWORD_CONFIG_BLOCK__

# SSH password authentication flag
ssh_pwauth: __SSH_PASSWORD_AUTH__

# Essential packages
packages:
  - qemu-guest-agent

# Configuration files
write_files:
  # SSH Certificate Authority public key
  - path: /etc/ssh/decloud_ca.pub
    permissions: '0644'
    content: |
      __CA_PUBLIC_KEY__

  # Universal SSH Password Authentication
  - path: /etc/ssh/sshd_config.d/99-decloud-password-auth.conf
    permissions: '0644'
    owner: root:root
    content: |
      # DeCloud: Enable password authentication for root
      # This file has priority over cloud-init's 50-cloud-init.conf
      PasswordAuthentication yes
      PermitRootLogin yes
      ChallengeResponseAuthentication no
      UsePAM yes

  # DeCloud Welcome Page HTML
  - path: /var/www/index.html
    permissions: '0644'
    content: |
      __INDEX_HTML__

  - path: /usr/local/bin/welcome-server.py
    permissions: '0755'
    content: |
      __WELCOME_SERVER_PY__

  # VM ID for attestation agent
  - path: /etc/decloud/vm-id
    permissions: '0644'
    content: __VM_ID__

  # Orchestrator URL for health checks (read-only, no secrets)
  - path: /etc/decloud/orchestrator-url
    permissions: '0644'
    content: __ORCHESTRATOR_URL__

  # Welcome page systemd service
  - path: /etc/systemd/system/welcome.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud Welcome Page with Caching
      After=network.target
      
      [Service]
      ExecStart=/usr/local/bin/welcome-server.py
      Restart=always
      WorkingDirectory=/var/www
      StandardOutput=journal
      StandardError=journal
      
      [Install]
      WantedBy=multi-user.target

  # Attestation agent binary (compiled Go, ~3MB base64)
  # Build: CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o decloud-agent
  # Encode: base64 decloud-agent > decloud-agent.b64
  - path: /usr/local/bin/decloud-agent
    permissions: '0755'
    encoding: base64
    content: |
      __ATTESTATION_AGENT_BASE64__

  # Attestation agent systemd service
  - path: /etc/systemd/system/decloud-agent.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud Ephemeral Attestation Agent
      After=network.target
      Documentation=https://docs.decloud.network/attestation
      
      [Service]
      Type=simple
      ExecStart=/usr/local/bin/decloud-agent
      Restart=always
      RestartSec=5
      
      # Security hardening
      NoNewPrivileges=yes
      ProtectSystem=strict
      ProtectHome=yes
      PrivateTmp=yes
      
      # Only needs to read /proc/* and /etc/machine-id
      ReadOnlyPaths=/proc /sys
      ReadWritePaths=/var/log
      
      # Logging
      StandardOutput=journal
      StandardError=journal
      SyslogIdentifier=decloud-agent
      
      [Install]
      WantedBy=multi-user.target

# Runtime commands
runcmd:
  # Start QEMU guest agent
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  
  # Configure SSH Certificate Authority
  - |
    cat >> /etc/ssh/sshd_config << 'DECLOUD_EOF'
    
    # DeCloud: SSH Certificate Authority
    TrustedUserCAKeys /etc/ssh/decloud_ca.pub
    AuthorizedPrincipalsFile /etc/ssh/auth_principals/%u
    DECLOUD_EOF
  
  # Create SSH principals for certificate-based auth
  - mkdir -p /etc/ssh/auth_principals
  - echo vm-__VM_ID__ > /etc/ssh/auth_principals/root
  - chmod 644 /etc/ssh/auth_principals/root

  # Create decloud config directory
  - mkdir -p /etc/decloud

  # Enable and start attestation agent
  - systemctl daemon-reload
  - systemctl enable decloud-agent
  - systemctl start decloud-agent
  # Log startup
  - echo "DeCloud Attestation Agent started" | systemd-cat -t decloud-agent
  
  # Start welcome page service
  - systemctl daemon-reload
  - systemctl enable --now welcome
  
  # Restart SSH to apply all configurations
  - systemctl restart sshd || systemctl restart ssh


final_message: "DeCloud VM __VM_NAME__ is ready!"