#cloud-config
# DeCloud Relay VM Cloud-Init Configuration
# This VM serves as a WireGuard relay for CGNAT nodes
# Version: 3.0 (with comprehensive debug dashboard)

hostname: __VM_NAME__
manage_etc_hosts: true

# =====================================================
# SYSTEM PACKAGES
# =====================================================
packages:
  - wireguard
  - wireguard-tools
  - nginx
  - fail2ban
  - qemu-guest-agent
  - python3
  - python3-pip
  - curl
  - jq
  - htop
  - iftop
  - net-tools
  - openssl

# =====================================================
# SYSTEM CONFIGURATION
# =====================================================
write_files:
  # WireGuard configuration (includes orchestrator as peer)
  - path: /etc/wireguard/wg-relay-server.conf
    permissions: '0600'
    content: |
      [Interface]
      # Relay server listening on all interfaces
      Address = 10.20.0.254/24
      PrivateKey = __WIREGUARD_PRIVATE_KEY__
      ListenPort = 51820
      
      # Enable IP forwarding
      PostUp = iptables -A FORWARD -i wg-relay-server -j ACCEPT
      PostUp = iptables -A FORWARD -o wg-relay-server -j ACCEPT
      PostUp = bash -c 'DEFAULT_IFACE=$(ip route | grep default | awk "{print \$5}"); iptables -t nat -A POSTROUTING -o $DEFAULT_IFACE -j MASQUERADE'
      PreDown = iptables -D FORWARD -i wg-relay-server -j ACCEPT
      PreDown = iptables -D FORWARD -o wg-relay-server -j ACCEPT
      PreDown = bash -c 'DEFAULT_IFACE=$(ip route | grep default | awk "{print \$5}"); iptables -t nat -D POSTROUTING -o $DEFAULT_IFACE -j MASQUERADE'
      
      # Orchestrator peer (pre-configured during provisioning)
      [Peer]
      # DeCloud Orchestrator
      PublicKey = __ORCHESTRATOR_PUBLIC_KEY__
      Endpoint = __ORCHESTRATOR_IP__:__ORCHESTRATOR_PORT__
      AllowedIPs = 10.20.0.1/32
      PersistentKeepalive = 25
      
      # NOTE: CGNAT nodes will be added dynamically by relay API

  # Store relay private key separately
  - path: /etc/wireguard/private.key
    permissions: '0600'
    content: |
      __WIREGUARD_PRIVATE_KEY__

  # Store relay public key
  - path: /etc/wireguard/public.key
    permissions: '0644'
    content: |
      __WIREGUARD_PUBLIC_KEY__

  # Nginx reverse proxy configuration
  - path: /etc/nginx/sites-available/relay-proxy
    permissions: '0644'
    content: |
      # HTTP proxy for CGNAT node traffic
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          
          server_name _;
          
          # Health check
          location /health {
              return 200 "OK\n";
              add_header Content-Type text/plain;
          }

          # Proxy to relay API (dashboard and management)
          location / {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
          
          # Proxy to CGNAT nodes (added dynamically)
          # Managed by relay API
      }

  # Relay management API
  - path: /etc/systemd/system/decloud-relay-api.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud Relay Management API
      After=network.target wg-quick@wg-relay-server.service
      Wants=wg-quick@wg-relay-server.service
      
      [Service]
      Type=simple
      ExecStart=/usr/bin/python3 /opt/decloud-relay/api.py
      Restart=always
      RestartSec=10
      
      [Install]
      WantedBy=multi-user.target

  # Dashboard static files (loaded from external templates)
  - path: /opt/decloud-relay/static/dashboard.html
    permissions: '0644'
    content: |
      __DASHBOARD_HTML__

  - path: /opt/decloud-relay/static/dashboard.css
    permissions: '0644'
    content: |
      __DASHBOARD_CSS__

  - path: /opt/decloud-relay/static/dashboard.js
    permissions: '0644'
    content: |
      __DASHBOARD_JS__

  # Relay API script (Python - loaded from external template)
  - path: /opt/decloud-relay/api.py
    permissions: '0755'
    content: |
      __RELAY_API__

  # DeCloud relay metadata
  - path: /etc/decloud/relay-info.json
    permissions: '0644'
    content: |
      {
        "relay_id": "__VM_ID__",
        "relay_name": "__VM_NAME__",
        "region": "__RELAY_REGION__",
        "max_capacity": __RELAY_CAPACITY__,
        "wireguard_endpoint": "__PUBLIC_IP__:51820",
        "wireguard_public_key": "__WIREGUARD_PUBLIC_KEY__",
        "orchestrator_public_key": "__ORCHESTRATOR_PUBLIC_KEY__",
        "created_at": "__TIMESTAMP__",
        "version": "3.0"
      }

# =====================================================
# RUNTIME COMMANDS
# =====================================================
runcmd:
  # Enable IP forwarding (required for relay functionality)
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf
  - sysctl -p
  
  # Configure firewall (UFW) for relay functionality  
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw default allow routed  # CRITICAL: Allow forwarded traffic
  - ufw allow 22/tcp comment "SSH"
  - ufw allow 51820/udp comment "WireGuard"
  - ufw allow 80/tcp comment "HTTP Proxy"
  - ufw allow 8080/tcp comment "Relay API"
  
  # Allow forwarding on WireGuard interface (must be before enable)
  - ufw route allow in on wg-relay-server
  - ufw route allow out on wg-relay-server
  
  # Enable UFW
  - ufw --force enable
  
  # Enable and start QEMU guest agent
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  
  # Start WireGuard (orchestrator peer already configured)
  - systemctl enable wg-quick@wg-relay-server
  - systemctl start wg-relay-server 2>/dev/null || wg-quick up wg-relay-server

  # Verify orchestrator peer is configured
  - wg show wg-relay-server | grep -A 5 "__ORCHESTRATOR_PUBLIC_KEY__" || echo "WARNING - Orchestrator peer not found!"

  # Configure routes for CGNAT node subnets through WireGuard
  - |
    echo "Configuring routes for CGNAT nodes..."
    # Add route for entire relay network through WireGuard interface
    ip route add 10.20.0.0/16 dev wg-relay-server 2>/dev/null || echo "Route already exists"
    
    # Make route persistent (if using netplan)
    mkdir -p /etc/network
    echo "10.20.0.0/16 dev wg-relay-server scope link" >> /etc/network/routes 2>/dev/null || true
    
    echo "Routes configured successfully"

  # Wait for WireGuard to be fully up
  - |
    for i in {1..10}; do
      if wg show wg-relay-server &>/dev/null; then
        echo "WireGuard interface ready"
        break
      fi
      sleep 2
    done

  # Notify orchestrator that relay is ready
  - |
    cat > /usr/local/bin/notify-orchestrator.sh <<'EOF'
    #!/bin/bash
    ORCHESTRATOR_URL="__ORCHESTRATOR_URL__"
    NODE_ID="__NODE_ID__"
    RELAY_VM_ID="__VM_ID__"
    PUBLIC_KEY="__WIREGUARD_PUBLIC_KEY__"
    PUBLIC_IP="__PUBLIC_IP__"
    
    # Read WireGuard private key
    WIREGUARD_PRIVATE_KEY=$(cat /etc/wireguard/private.key | tr -d '\n')

    # Compute callback token using WireGuard private key
    MESSAGE="${NODE_ID}:${RELAY_VM_ID}"
    TOKEN=$(echo -n "$MESSAGE" | openssl dgst -sha256 -hmac "$WIREGUARD_PRIVATE_KEY" -binary | base64)
    
    # Call orchestrator callback endpoint
    curl -X POST "$ORCHESTRATOR_URL/api/relay/register-callback" \
      -H "Content-Type: application/json" \
      -H "X-Relay-Token: $TOKEN" \
      -d "{
        \"nodeId\": \"$NODE_ID\",
        \"relayVmId\": \"$RELAY_VM_ID\",
        \"wireGuardPublicKey\": \"$PUBLIC_KEY\",
        \"wireGuardEndpoint\": \"$PUBLIC_IP:51820\"
      }" \
      --max-time 10 \
      --retry 3 \
      --retry-delay 5
    
    if [ $? -eq 0 ]; then
      echo "✓ Successfully notified orchestrator - relay is now active"
    else
      echo "⚠ Failed to notify orchestrator - will retry on health check"
    fi
    EOF
    
  - chmod +x /usr/local/bin/notify-orchestrator.sh
  - /usr/local/bin/notify-orchestrator.sh &

  # Notify node agent that relay VM is ready for NAT configuration
  - |
    cat > /usr/local/bin/notify-nat-ready.sh <<'EOF'
    #!/bin/bash
    
    # Dynamically detect the gateway IP (host from VM perspective)
    # Method 1: Default route (most reliable)
    GATEWAY_IP=$(ip route | grep default | awk '{print $3}' | head -1)

    # Method 2: Parse route to external IP
    if [ -z "$GATEWAY_IP" ]; then
      GATEWAY_IP=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'via \K[\d.]+' | head -1)
    fi

    # Method 3: Fallback to common libvirt gateway
    if [ -z "$GATEWAY_IP" ]; then
      echo "⚠ Using fallback gateway 192.168.122.1"
      GATEWAY_IP="192.168.122.1"
    fi
    
    NODE_AGENT_URL="http://${GATEWAY_IP}:5100"
    VM_ID="__VM_ID__"
    
    echo "Detected gateway IP: $GATEWAY_IP"
    echo "Node agent URL: $NODE_AGENT_URL"
    
    # Wait for network to be fully up and obtain IP using dynamic interface detection
    echo "Waiting for IP address..."
    for i in {1..30}; do
      # Dynamically detect the default route interface (works for eth0, enp1s0, ens3, etc.)
      DEFAULT_INTERFACE=$(ip route get 1.1.1.1 2>/dev/null | grep -oP 'dev \K\S+' | head -1)
      
      if [ -n "$DEFAULT_INTERFACE" ]; then
        VM_IP=$(ip -4 addr show "$DEFAULT_INTERFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
        
        if [ -n "$VM_IP" ]; then
          echo "✓ Obtained IP address: $VM_IP on interface $DEFAULT_INTERFACE"
          break
        fi
      fi
      sleep 2
    done
    
    if [ -z "$VM_IP" ]; then
      echo "❌ Failed to obtain IP address after 60 seconds"
      exit 1
    fi
    
    # Use host machine ID for authentication (passed from node agent)
    MACHINE_ID="__HOST_MACHINE_ID__"

    echo "Using machine ID for authentication: ${MACHINE_ID:0:8}..."
    
    # Compute callback token using HMAC-SHA256
    MESSAGE="${VM_ID}:${VM_IP}"
    TOKEN=$(echo -n "$MESSAGE" | openssl dgst -sha256 -hmac "$MACHINE_ID" -binary | base64)
    
    echo "Notifying node agent at $NODE_AGENT_URL..."
    
    # Call node agent NAT callback endpoint
    RESPONSE=$(curl -X POST "$NODE_AGENT_URL/api/relay/nat-ready" \
      -H "Content-Type: application/json" \
      -H "X-Relay-Token: $TOKEN" \
      -d "{
        \"vmId\": \"$VM_ID\",
        \"vmIp\": \"$VM_IP\"
      }" \
      --max-time 10 \
      --retry 3 \
      --retry-delay 5 \
      -w "\nHTTP_CODE:%{http_code}" \
      2>&1)
    
    HTTP_CODE=$(echo "$RESPONSE" | grep -oP 'HTTP_CODE:\K\d+')
    
    if [ "$HTTP_CODE" = "200" ]; then
      echo "✓ Successfully notified node agent - NAT rule configured!"
      echo "✓ CGNAT nodes can now connect to this relay"
      logger -t decloud-relay "NAT rule configured successfully for $VM_IP via gateway $GATEWAY_IP"
    else
      echo "⚠ Failed to notify node agent (HTTP $HTTP_CODE)"
      echo "Response: $RESPONSE"
      logger -t decloud-relay "Failed to configure NAT rule - manual intervention required"
    fi
    EOF
    
  - chmod +x /usr/local/bin/notify-nat-ready.sh
  
  # Run notification script in background (non-blocking)
  - /usr/local/bin/notify-nat-ready.sh >> /var/log/decloud-nat-callback.log 2>&1 &
  
  # Log the callback attempt
  - 'echo "NAT callback notification scheduled at $(date)" >> /var/log/decloud-relay-bootstrap.log'
  
  # Verify orchestrator peer is configured
  - wg show wg-relay-server | grep -A 5 "__ORCHESTRATOR_PUBLIC_KEY__" || echo "WARNING - Orchestrator peer not found!"
  
  # Configure and start Nginx
  - ln -sf /etc/nginx/sites-available/relay-proxy /etc/nginx/sites-enabled/
  - rm -f /etc/nginx/sites-enabled/default
  - nginx -t
  - systemctl enable nginx
  - systemctl restart nginx
  
  # Start relay management API
  - systemctl daemon-reload
  - systemctl enable decloud-relay-api
  - systemctl start decloud-relay-api
  
  # Configure fail2ban for SSH protection
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Create directory for relay API
  - mkdir -p /opt/decloud-relay/static
  - mkdir -p /etc/decloud
  
  # Log completion
  - 'echo "DeCloud relay VM bootstrap complete at $(date)" > /var/log/decloud-relay-bootstrap.log'
  - 'echo "Relay ID: __VM_ID__" >> /var/log/decloud-relay-bootstrap.log'
  - 'echo "Region: __RELAY_REGION__" >> /var/log/decloud-relay-bootstrap.log'
  - 'echo "WireGuard Public Key: __WIREGUARD_PUBLIC_KEY__" >> /var/log/decloud-relay-bootstrap.log'
  - 'echo "Orchestrator Public Key: __ORCHESTRATOR_PUBLIC_KEY__" >> /var/log/decloud-relay-bootstrap.log'
  - 'echo "Orchestrator peer configured: YES" >> /var/log/decloud-relay-bootstrap.log'

final_message: "DeCloud Relay VM __VM_NAME__ is ready! Dashboard: http://__PUBLIC_IP__:8080/ WireGuard endpoint: __PUBLIC_IP__:51820"