#cloud-config
# DeCloud Relay VM Cloud-Init Configuration
# This VM serves as a WireGuard relay for CGNAT nodes
# Version: 4.1 (FIXED - All issues resolved)

hostname: __VM_NAME__
manage_etc_hosts: true

# =====================================================
# SYSTEM PACKAGES
# =====================================================
packages:
  - wireguard
  - wireguard-tools
  - nginx
  - fail2ban
  - qemu-guest-agent
  - python3
  - python3-pip
  - curl
  - jq
  - htop
  - iftop
  - net-tools
  - openssl

# =====================================================
# SYSTEM CONFIGURATION
# =====================================================
write_files:
  # WireGuard configuration (includes orchestrator as peer)
  - path: /etc/wireguard/wg-relay-server.conf
    permissions: '0600'
    content: |
      [Interface]
      # Relay server listening on all interfaces
      # Each relay gets unique subnet: 10.20.{1-254}.0/24
      # This relay's subnet: __RELAY_SUBNET__
      Address = 10.20.__RELAY_SUBNET__.254/24
      PrivateKey = __WIREGUARD_PRIVATE_KEY__
      ListenPort = 51820
      
      # Enable IP forwarding
      PostUp = iptables -A FORWARD -i wg-relay-server -j ACCEPT
      PostUp = iptables -A FORWARD -o wg-relay-server -j ACCEPT
      PostUp = bash -c 'DEFAULT_IFACE=$(ip route | grep default | awk "{print \$5}"); iptables -t nat -A POSTROUTING -o $DEFAULT_IFACE -j MASQUERADE'
      PreDown = iptables -D FORWARD -i wg-relay-server -j ACCEPT
      PreDown = iptables -D FORWARD -o wg-relay-server -j ACCEPT
      PreDown = bash -c 'DEFAULT_IFACE=$(ip route | grep default | awk "{print \$5}"); iptables -t nat -D POSTROUTING -o $DEFAULT_IFACE -j MASQUERADE'
      
      # Orchestrator peer (pre-configured during provisioning)
      [Peer]
      # DeCloud Orchestrator
      PublicKey = __ORCHESTRATOR_PUBLIC_KEY__
      Endpoint = __ORCHESTRATOR_IP__:__ORCHESTRATOR_PORT__
      # Orchestrator always uses 10.20.0.1, not per-subnet IP
      AllowedIPs = 10.20.0.1/32
      PersistentKeepalive = 25
      
      # NOTE: CGNAT nodes will be added dynamically by relay API

  # Store relay private key separately
  - path: /etc/wireguard/private.key
    permissions: '0600'
    content: |
      __WIREGUARD_PRIVATE_KEY__

  # Store relay public key
  - path: /etc/wireguard/public.key
    permissions: '0644'
    content: |
      __WIREGUARD_PUBLIC_KEY__

  # Store relay subnet for reference
  - path: /etc/decloud/relay-subnet
    permissions: '0644'
    content: |
      __RELAY_SUBNET__

  # Nginx reverse proxy configuration
  - path: /etc/nginx/sites-available/relay-proxy
    permissions: '0644'
    content: |
      # WebSocket upgrade header mapping
      map $http_upgrade $connection_upgrade {
          default upgrade;
          '' close;
      }

      # HTTP proxy for CGNAT node traffic
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
    
          server_name _;
    
          # Health check
          location /health {
              return 200 "OK\n";
              add_header Content-Type text/plain;
          }

          # Static files (dashboard CSS/JS) → Relay API
          location /static/ {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
        
              # Cache static files
              proxy_cache_valid 200 1h;
              add_header Cache-Control "public, max-age=3600";
          }

          # Relay API dashboard (explicit path)
          location /api/relay/ {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }

          # Dashboard root (only for relay dashboard hostname)
          location = / {
              # If accessing relay directly (not a VM subdomain), show dashboard
              if ($host ~* "^[0-9.]+$|^relay-") {
                  proxy_pass http://127.0.0.1:8080;
                  break;
              }
        
              # Otherwise, proxy to VM
              proxy_pass http://127.0.0.1:8081;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
        
              # Long timeout for VM traffic
              proxy_connect_timeout 30s;
              proxy_send_timeout 90s;
              proxy_read_timeout 90s;
          }

          # All wildcard subdomain traffic → HTTP Proxy Service
          location / {
              proxy_pass http://127.0.0.1:8081;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
        
              # Timeouts
              proxy_connect_timeout 30s;
              proxy_send_timeout 90s;
              proxy_read_timeout 90s;
        
              # Buffering
              proxy_buffering off;
              proxy_request_buffering off;
        
              # WebSocket support
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
          }
      }

  # FIXED: Relay management API with Wants instead of Requires
  - path: /etc/systemd/system/decloud-relay-api.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud Relay Management API
      After=network.target wg-quick@wg-relay-server.service
      Wants=wg-quick@wg-relay-server.service
      
      [Service]
      Type=simple
      Restart=always
      RestartSec=5
      WorkingDirectory=/opt/decloud-relay
      ExecStart=/usr/bin/python3 /opt/decloud-relay/relay-api.py
      StandardOutput=journal
      StandardError=journal
      
      [Install]
      WantedBy=multi-user.target

  # FIXED: HTTP Proxy with Wants instead of Requires
  - path: /etc/systemd/system/decloud-relay-http-proxy.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud Relay HTTP Proxy
      After=network.target wg-quick@wg-relay-server.service nginx.service
      Wants=wg-quick@wg-relay-server.service nginx.service

      [Service]
      Type=simple
      Restart=always
      RestartSec=5
      WorkingDirectory=/opt/decloud-relay
      ExecStart=/usr/bin/python3 /opt/decloud-relay/http-proxy.py
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=multi-user.target

  # Systemd service for NAT callback
  - path: /etc/systemd/system/decloud-relay-nat-callback.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud Relay NAT Configuration Callback
      After=network-online.target
      Wants=network-online.target
      
      [Service]
      Type=oneshot
      ExecStartPre=/bin/bash -c 'if [ -f /var/lib/decloud/nat-callback-complete ]; then echo "NAT callback already completed"; exit 0; fi'
      ExecStart=/usr/local/bin/notify-nat-ready.sh
      ExecStartPost=/bin/bash -c 'mkdir -p /var/lib/decloud && touch /var/lib/decloud/nat-callback-complete'
      RemainAfterExit=yes
      StandardOutput=journal
      StandardError=journal
      Restart=on-failure
      RestartSec=5s
      StartLimitBurst=3
      TimeoutStartSec=30s
      
      [Install]
      WantedBy=multi-user.target

  # NAT callback script
  - path: /usr/local/bin/notify-nat-ready.sh
    permissions: '0755'
    content: |
      __NOTIFY_NAT_READY__

  # Dashboard static files (loaded from external templates)
  - path: /opt/decloud-relay/static/dashboard.html
    permissions: '0644'
    content: |
      __DASHBOARD_HTML__

  - path: /opt/decloud-relay/static/dashboard.css
    permissions: '0644'
    content: |
      __DASHBOARD_CSS__

  - path: /opt/decloud-relay/static/dashboard.js
    permissions: '0644'
    content: |
      __DASHBOARD_JS__

  # Relay API script (Python - loaded from external template)
  - path: /opt/decloud-relay/relay-api.py
    permissions: '0755'
    content: |
      __RELAY_API__

  # HTTP Proxy Script (loaded from external template)
  - path: /opt/decloud-relay/http-proxy.py
    permissions: '0755'
    content: |
      __RELAY_HTTP_PROXY__

  # FIXED: Relay metadata JSON (removed embedded shell command)
  - path: /etc/decloud/relay-metadata.json
    permissions: '0644'
    content: |
      {
        "node_id": "__NODE_ID__",
        "relay_id": "__VM_ID__",
        "vm_id": "__VM_ID__",
        "relay_name": "__VM_NAME__",
        "region": "__RELAY_REGION__",
        "relay_subnet": __RELAY_SUBNET__,
        "tunnel_ip": "10.20.__RELAY_SUBNET__.254",
        "max_capacity": __RELAY_CAPACITY__,
        "wireguard_endpoint": "__PUBLIC_IP__:51820",
        "wireguard_public_key": "__WIREGUARD_PUBLIC_KEY__",
        "orchestrator_public_key": "__ORCHESTRATOR_PUBLIC_KEY__",
        "created_at": "__TIMESTAMP__",
        "version": "4.1"
      }

# =====================================================
# RUNTIME COMMANDS
# =====================================================
runcmd:
  # Enable IP forwarding (required for relay functionality)
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf
  - sysctl -p
  
  # Configure firewall (UFW)
  - ufw disable || true
  - systemctl stop ufw || true
  - systemctl disable ufw || true
  
  # Enable and start QEMU guest agent
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  
  # Start WireGuard manually first, then enable for boot
  - wg-quick up wg-relay-server
  - systemctl enable wg-quick@wg-relay-server

  # Verify orchestrator peer is configured
  - wg show wg-relay-server | grep -A 5 "__ORCHESTRATOR_PUBLIC_KEY__" || echo "WARNING - Orchestrator peer not found!"

  # Configure routes for relay subnet
  - |
    echo "Configuring routes for relay subnet..."
    RELAY_SUBNET="__RELAY_SUBNET__"
    ip route add 10.20.${RELAY_SUBNET}.0/24 dev wg-relay-server 2>/dev/null || echo "Route already exists"
    mkdir -p /etc/network
    echo "10.20.${RELAY_SUBNET}.0/24 dev wg-relay-server scope link" >> /etc/network/routes 2>/dev/null || true
    echo "Routes configured for subnet 10.20.${RELAY_SUBNET}.0/24"

  # Wait for WireGuard to be fully up
  - |
    for i in {1..10}; do
      if wg show wg-relay-server &>/dev/null; then
        echo "WireGuard interface ready"
        break
      fi
      sleep 2
    done

  # Create notify-orchestrator.sh script
  - |
    cat > /usr/local/bin/notify-orchestrator.sh <<'EOF'
    #!/bin/bash
    ORCHESTRATOR_URL="__ORCHESTRATOR_URL__"
    NODE_ID="__NODE_ID__"
    RELAY_VM_ID="__VM_ID__"
    PUBLIC_KEY="__WIREGUARD_PUBLIC_KEY__"
    PUBLIC_IP="__PUBLIC_IP__"
    RELAY_SUBNET="__RELAY_SUBNET__"
    TUNNEL_IP="10.20.${RELAY_SUBNET}.254"
    
    # Read WireGuard private key
    WIREGUARD_PRIVATE_KEY=$(cat /etc/wireguard/private.key | tr -d '\n')

    # Compute callback token
    MESSAGE="${NODE_ID}:${RELAY_VM_ID}"
    TOKEN=$(echo -n "$MESSAGE" | openssl dgst -sha256 -hmac "$WIREGUARD_PRIVATE_KEY" -binary | base64)
    
    # Call orchestrator callback endpoint
    RESPONSE=$(curl -X POST "$ORCHESTRATOR_URL/api/relay/register-callback" \
      -H "Content-Type: application/json" \
      -H "X-Relay-Token: $TOKEN" \
      -d "{
        \"nodeId\": \"$NODE_ID\",
        \"relayVmId\": \"$RELAY_VM_ID\",
        \"wireGuardPublicKey\": \"$PUBLIC_KEY\",
        \"wireGuardEndpoint\": \"$PUBLIC_IP:51820\",
        \"relaySubnet\": $RELAY_SUBNET,
        \"tunnelIp\": \"$TUNNEL_IP\"
      }" \
      --max-time 10 \
      --retry 3 \
      --retry-delay 5 \
      -w "\nHTTP_CODE:%{http_code}" \
      -s \
      2>&1)
    
    HTTP_CODE=$(echo "$RESPONSE" | grep -oP 'HTTP_CODE:\K\d+')
    
    if [ "$HTTP_CODE" = "200" ]; then
      echo "✓ Successfully notified orchestrator - relay subnet $RELAY_SUBNET is now active"
      logger -t decloud-relay "Orchestrator notified - relay active"
      exit 0
    else
      echo "⚠ Failed to notify orchestrator (HTTP ${HTTP_CODE:-timeout})"
      logger -t decloud-relay "Orchestrator notification failed"
      exit 1
    fi
    EOF
    
  - chmod +x /usr/local/bin/notify-orchestrator.sh

  # Start NAT callback service
  - systemctl daemon-reload
  - systemctl enable decloud-relay-nat-callback.service
  - systemctl start decloud-relay-nat-callback.service

  # Configure and start Nginx
  - ln -sf /etc/nginx/sites-available/relay-proxy /etc/nginx/sites-enabled/
  - rm -f /etc/nginx/sites-enabled/default
  - nginx -t
  - systemctl enable nginx
  - systemctl restart nginx

  # Create directories
  - mkdir -p /opt/decloud-relay/static
  - mkdir -p /etc/decloud

  # Start relay services
  - systemctl daemon-reload
  - systemctl enable decloud-relay-http-proxy
  - systemctl start decloud-relay-http-proxy
  - sleep 2
  - systemctl is-active decloud-relay-http-proxy || echo "WARNING - HTTP proxy failed to start"
  
  - systemctl enable decloud-relay-api
  - systemctl start decloud-relay-api
  - systemctl is-active decloud-relay-api || echo "WARNING - Relay API failed to start"

  # Configure fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Log completion
  - 'echo "DeCloud relay VM bootstrap complete at $(date)" >> /var/log/decloud-relay-bootstrap.log'
  - 'echo "Relay ID: __VM_ID__" >> /var/log/decloud-relay-bootstrap.log'
  - 'echo "Relay Subnet: __RELAY_SUBNET__ (10.20.__RELAY_SUBNET__.0/24)" >> /var/log/decloud-relay-bootstrap.log'
  - 'echo "Tunnel IP: 10.20.__RELAY_SUBNET__.254" >> /var/log/decloud-relay-bootstrap.log'
  - 'echo "Region: __RELAY_REGION__" >> /var/log/decloud-relay-bootstrap.log'

final_message: "DeCloud Relay VM __VM_NAME__ is ready! Subnet: 10.20.__RELAY_SUBNET__.0/24, Gateway: 10.20.__RELAY_SUBNET__.254"