#cloud-config
# DeCloud Relay VM Cloud-Init Configuration
# This VM serves as a WireGuard relay for CGNAT nodes
# Version: 2.0 (with orchestrator peer pre-configured)

hostname: __VM_NAME__

# =====================================================
# SYSTEM PACKAGES
# =====================================================
packages:
  - wireguard
  - wireguard-tools
  - nginx
  - fail2ban
  - qemu-guest-agent
  - python3
  - python3-pip
  - curl
  - jq

# =====================================================
# SYSTEM CONFIGURATION
# =====================================================
write_files:
  # WireGuard configuration (includes orchestrator as peer)
  - path: /etc/wireguard/wg-relay-server.conf
    permissions: '0600'
    content: |
      [Interface]
      # Relay server listening on all interfaces
      Address = 10.20.0.254/24
      PrivateKey = __RELAY_PRIVATE_KEY__
      ListenPort = 51820
      
      # Enable IP forwarding
      PostUp = iptables -A FORWARD -i wg-relay-server -j ACCEPT
      PostUp = iptables -A FORWARD -o wg-relay-server -j ACCEPT
      PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      PreDown = iptables -D FORWARD -i wg-relay-server -j ACCEPT
      PreDown = iptables -D FORWARD -o wg-relay-server -j ACCEPT
      PreDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      
      # Orchestrator peer (pre-configured during provisioning)
      [Peer]
      # DeCloud Orchestrator
      PublicKey = __ORCHESTRATOR_PUBLIC_KEY__
      AllowedIPs = 10.20.0.1/32
      PersistentKeepalive = 25
      
      # NOTE: CGNAT nodes will be added dynamically by relay API

  # Store relay private key separately
  - path: /etc/wireguard/private.key
    permissions: '0600'
    content: |
      __RELAY_PRIVATE_KEY__

  # Store relay public key
  - path: /etc/wireguard/public.key
    permissions: '0644'
    content: |
      __RELAY_PUBLIC_KEY__

  # Nginx reverse proxy configuration
  - path: /etc/nginx/sites-available/relay-proxy
    permissions: '0644'
    content: |
      # HTTP proxy for CGNAT node traffic
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          
          server_name _;
          
          # Health check
          location /health {
              return 200 "OK\n";
              add_header Content-Type text/plain;
          }
          
          # Proxy to CGNAT nodes (added dynamically)
          # Managed by relay API
      }

  # Relay management API
  - path: /etc/systemd/system/decloud-relay-api.service
    permissions: '0644'
    content: |
      [Unit]
      Description=DeCloud Relay Management API
      After=network.target wg-quick@wg-relay-server.service
      Wants=wg-quick@wg-relay-server.service
      
      [Service]
      Type=simple
      ExecStart=/usr/bin/python3 /opt/decloud-relay/api.py
      Restart=always
      RestartSec=10
      
      [Install]
      WantedBy=multi-user.target

  # Relay API script (Python)
  - path: /opt/decloud-relay/api.py
    permissions: '0755'
    content: |
      #!/usr/bin/env python3
      """
      DeCloud Relay Management API
      Handles dynamic CGNAT peer management
      """
      import json
      import subprocess
      import logging
      from http.server import HTTPServer, BaseHTTPRequestHandler
      
      logging.basicConfig(level=logging.INFO)
      logger = logging.getLogger(__name__)
      
      RELAY_ID = "__VM_ID__"
      RELAY_CAPACITY = __RELAY_CAPACITY__
      RELAY_REGION = "__RELAY_REGION__"
      
      class RelayAPIHandler(BaseHTTPRequestHandler):
          def log_message(self, format, *args):
              logger.info("%s - - [%s] %s" % (
                  self.address_string(),
                  self.log_date_time_string(),
                  format % args))
          
          def do_GET(self):
              if self.path == '/api/relay/status':
                  self.send_response(200)
                  self.send_header('Content-Type', 'application/json')
                  self.end_headers()
                  
                  # Get WireGuard status
                  try:
                      result = subprocess.run(
                          ['wg', 'show', 'wg-relay-server'],
                          capture_output=True,
                          text=True)
                      peer_count = result.stdout.count('peer:')
                      
                      # Orchestrator peer doesn't count toward capacity
                      cgnat_peer_count = max(0, peer_count - 1)
                  except:
                      cgnat_peer_count = 0
                  
                  status = {
                      'relay_id': RELAY_ID,
                      'status': 'online',
                      'region': RELAY_REGION,
                      'max_capacity': RELAY_CAPACITY,
                      'current_load': cgnat_peer_count,
                      'available_slots': max(0, RELAY_CAPACITY - cgnat_peer_count)
                  }
                  self.wfile.write(json.dumps(status).encode())
              else:
                  self.send_error(404)
          
          def do_POST(self):
              if self.path == '/api/relay/add-peer':
                  self.add_wireguard_peer()
              elif self.path == '/api/relay/remove-peer':
                  self.remove_wireguard_peer()
              else:
                  self.send_error(404)
          
          def add_wireguard_peer(self):
              try:
                  content_length = int(self.headers['Content-Length'])
                  post_data = self.rfile.read(content_length)
                  peer = json.loads(post_data)
                  
                  if 'public_key' not in peer or 'tunnel_ip' not in peer:
                      self.send_error(400, 'Missing public_key or tunnel_ip')
                      return
                  
                  # Add WireGuard peer
                  cmd = [
                      'wg', 'set', 'wg-relay-server',
                      'peer', peer['public_key'],
                      'allowed-ips', peer['tunnel_ip'] + '/32'
                  ]
                  
                  if 'persistent_keepalive' in peer:
                      cmd.extend(['persistent-keepalive', str(peer['persistent_keepalive'])])
                  
                  result = subprocess.run(cmd, capture_output=True)
                  
                  if result.returncode == 0:
                      logger.info(f"Added WireGuard peer: {peer['public_key'][:12]}... -> {peer['tunnel_ip']}")
                      
                      # Persist configuration
                      subprocess.run(['wg-quick', 'save', 'wg-relay-server'])
                      
                      self.send_response(200)
                      self.send_header('Content-Type', 'application/json')
                      self.end_headers()
                      self.wfile.write(json.dumps({
                          'status': 'success',
                          'message': 'Peer added successfully'
                      }).encode())
                  else:
                      logger.error(f"Failed to add peer: {result.stderr.decode()}")
                      self.send_error(500, result.stderr.decode())
              except Exception as e:
                  logger.exception("Error adding peer")
                  self.send_error(500, str(e))
          
          def remove_wireguard_peer(self):
              try:
                  content_length = int(self.headers['Content-Length'])
                  post_data = self.rfile.read(content_length)
                  peer = json.loads(post_data)
                  
                  if 'public_key' not in peer:
                      self.send_error(400, 'Missing public_key')
                      return
                  
                  cmd = ['wg', 'set', 'wg-relay-server', 'peer', peer['public_key'], 'remove']
                  result = subprocess.run(cmd, capture_output=True)
                  
                  if result.returncode == 0:
                      logger.info(f"Removed WireGuard peer: {peer['public_key'][:12]}...")
                      subprocess.run(['wg-quick', 'save', 'wg-relay-server'])
                      
                      self.send_response(200)
                      self.send_header('Content-Type', 'application/json')
                      self.end_headers()
                      self.wfile.write(json.dumps({
                          'status': 'success',
                          'message': 'Peer removed successfully'
                      }).encode())
                  else:
                      logger.error(f"Failed to remove peer: {result.stderr.decode()}")
                      self.send_error(500, result.stderr.decode())
              except Exception as e:
                  logger.exception("Error removing peer")
                  self.send_error(500, str(e))
      
      if __name__ == '__main__':
          server = HTTPServer(('0.0.0.0', 8080), RelayAPIHandler)
          logger.info(f"Relay API listening on port 8080")
          logger.info(f"Relay ID: {RELAY_ID}")
          logger.info(f"Region: {RELAY_REGION}")
          logger.info(f"Capacity: {RELAY_CAPACITY}")
          server.serve_forever()

  # DeCloud relay metadata
  - path: /etc/decloud/relay-info.json
    permissions: '0644'
    content: |
      {
        "relay_id": "__VM_ID__",
        "relay_name": "__VM_NAME__",
        "region": "__RELAY_REGION__",
        "max_capacity": __RELAY_CAPACITY__,
        "wireguard_endpoint": "__PUBLIC_IP__:51820",
        "wireguard_public_key": "__RELAY_PUBLIC_KEY__",
        "orchestrator_public_key": "__ORCHESTRATOR_PUBLIC_KEY__",
        "created_at": "__TIMESTAMP__",
        "version": "2.0"
      }

# =====================================================
# RUNTIME COMMANDS
# =====================================================
runcmd:
  # Enable IP forwarding (required for relay functionality)
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.conf
  - sysctl -p
  
  # Configure firewall (UFW)
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp comment "SSH"
  - ufw allow 51820/udp comment "WireGuard"
  - ufw allow 80/tcp comment "HTTP Proxy"
  - ufw allow 8080/tcp comment "Relay API"
  - ufw --force enable
  
  # Enable and start QEMU guest agent
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  
  # Start WireGuard (orchestrator peer already configured)
  - systemctl enable wg-quick@wg-relay-server
  - systemctl start wg-relay-server 2>/dev/null || wg-quick up wg-relay-server
  
  # Verify orchestrator peer is configured
  - wg show wg-relay-server | grep -A 5 "__ORCHESTRATOR_PUBLIC_KEY__" || echo "WARNING: Orchestrator peer not found!"
  
  # Configure and start Nginx
  - ln -sf /etc/nginx/sites-available/relay-proxy /etc/nginx/sites-enabled/
  - rm -f /etc/nginx/sites-enabled/default
  - nginx -t
  - systemctl enable nginx
  - systemctl restart nginx
  
  # Start relay management API
  - systemctl daemon-reload
  - systemctl enable decloud-relay-api
  - systemctl start decloud-relay-api
  
  # Configure fail2ban for SSH protection
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Create directory for relay API
  - mkdir -p /opt/decloud-relay
  - mkdir -p /etc/decloud
  
  # Log completion
  - echo "DeCloud relay VM bootstrap complete at $(date)" > /var/log/decloud-relay-bootstrap.log
  - echo "Relay ID: __VM_ID__" >> /var/log/decloud-relay-bootstrap.log
  - echo "Region: __RELAY_REGION__" >> /var/log/decloud-relay-bootstrap.log
  - echo "WireGuard Public Key: __RELAY_PUBLIC_KEY__" >> /var/log/decloud-relay-bootstrap.log
  - echo "Orchestrator Public Key: __ORCHESTRATOR_PUBLIC_KEY__" >> /var/log/decloud-relay-bootstrap.log
  - echo "Orchestrator peer configured: YES" >> /var/log/decloud-relay-bootstrap.log

final_message: "DeCloud Relay VM __VM_NAME__ is ready! Orchestrator peer pre-configured. WireGuard endpoint: __PUBLIC_IP__:51820"