#!/usr/bin/env bash
# install-dashboard.sh — DeCloud CLI Dashboard installer
#
# What this does:
#   1. Checks Python 3.11+
#   2. Creates a virtualenv at ~/.decloud/dashboard-venv
#   3. Installs requirements.txt into the venv
#   4. Writes the launcher shim to /usr/local/bin/decloud-dashboard
#   5. Patches cli/decloud so 'decloud dashboard' forwards to the shim
#
# Run as the node operator user (not root). sudo is used only for
# writing to /usr/local/bin and for patching /usr/local/bin/decloud.

set -euo pipefail

# ── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log_step()    { echo -e "\n${CYAN}▶ ${BOLD}${1}${NC}"; }
log_ok()      { echo -e "  ${GREEN}✓${NC} ${1}"; }
log_warn()    { echo -e "  ${YELLOW}⚠${NC}  ${1}"; }
log_error()   { echo -e "  ${RED}✗${NC} ${1}" >&2; }
log_info()    { echo -e "  ${1}"; }

# ── paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DASHBOARD_DIR="${SCRIPT_DIR}/dashboard"
VENV_DIR="${HOME}/.decloud/dashboard-venv"
SHIM="/usr/local/bin/decloud-dashboard"
DECLOUD_BIN="/usr/local/bin/decloud"
MIN_PYTHON_MINOR=11

# ── checks ────────────────────────────────────────────────────────────────────
log_step "Checking prerequisites"

check_python() {
    local py=""
    for candidate in python3 python3.12 python3.11; do
        if command -v "$candidate" &>/dev/null; then
            local minor
            minor=$("$candidate" -c "import sys; print(sys.version_info.minor)")
            local major
            major=$("$candidate" -c "import sys; print(sys.version_info.major)")
            if [[ "$major" -eq 3 && "$minor" -ge "$MIN_PYTHON_MINOR" ]]; then
                py="$candidate"
                break
            fi
        fi
    done
    if [[ -z "$py" ]]; then
        log_error "Python 3.${MIN_PYTHON_MINOR}+ not found."
        log_info  "Install it: sudo apt install python3.11  (Ubuntu/Debian)"
        exit 1
    fi
    echo "$py"
}

PYTHON=$(check_python)
log_ok "Python: $($PYTHON --version)"

if [[ ! -f "${DASHBOARD_DIR}/requirements.txt" ]]; then
    log_error "requirements.txt not found at ${DASHBOARD_DIR}/requirements.txt"
    exit 1
fi
log_ok "Dashboard source: ${DASHBOARD_DIR}"

# ── virtual environment ────────────────────────────────────────────────────────
log_step "Creating virtual environment at ${VENV_DIR}"

mkdir -p "$(dirname "$VENV_DIR")"
if [[ ! -d "${VENV_DIR}" ]]; then
    "$PYTHON" -m venv "${VENV_DIR}"
    log_ok "Venv created"
else
    log_ok "Venv already exists — reusing"
fi

# ── dependencies ───────────────────────────────────────────────────────────────
log_step "Installing Python dependencies"

"${VENV_DIR}/bin/pip" install --quiet --upgrade pip
"${VENV_DIR}/bin/pip" install --quiet -r "${DASHBOARD_DIR}/requirements.txt"
log_ok "Dependencies installed"

# ── launcher shim ──────────────────────────────────────────────────────────────
log_step "Writing launcher shim → ${SHIM}"

sudo tee "${SHIM}" > /dev/null <<SHIM_EOF
#!/usr/bin/env bash
# DeCloud Dashboard launcher — auto-generated by install-dashboard.sh
# Do not edit; re-run install-dashboard.sh to update.
VENV="${VENV_DIR}"
DASHBOARD_DIR="${DASHBOARD_DIR}"
exec "\${VENV}/bin/python" -m dashboard "\$@"
SHIM_EOF

sudo chmod +x "${SHIM}"
log_ok "Shim written: ${SHIM}"

# ── patch cli/decloud ──────────────────────────────────────────────────────────
log_step "Patching cli/decloud to add 'dashboard' subcommand"

patch_decloud() {
    local target="$1"
    if [[ ! -f "$target" ]]; then
        log_warn "cli/decloud not found at $target — skipping patch"
        return
    fi
    if grep -q '"dashboard"' "$target" 2>/dev/null; then
        log_ok "cli/decloud already has 'dashboard' subcommand — skipping"
        return
    fi

    # Append a dashboard case to the command dispatcher
    sudo tee -a "$target" > /dev/null <<'PATCH_EOF'

# ── dashboard subcommand (added by install-dashboard.sh) ──────────────────────
if [[ "${1:-}" == "dashboard" ]]; then
    shift
    if ! command -v decloud-dashboard &>/dev/null; then
        echo "decloud-dashboard not installed. Run: cli/install-dashboard.sh" >&2
        exit 1
    fi
    exec decloud-dashboard "$@"
fi
PATCH_EOF
    log_ok "Patched: $target"
}

# Try the installed bin first, then the repo copy
if [[ -f "${DECLOUD_BIN}" ]]; then
    patch_decloud "${DECLOUD_BIN}"
elif [[ -f "${SCRIPT_DIR}/decloud" ]]; then
    patch_decloud "${SCRIPT_DIR}/decloud"
else
    log_warn "Could not find cli/decloud to patch — run 'decloud-dashboard' directly"
fi

# ── auto-fetch credentials ────────────────────────────────────────────────────
log_step "Auto-fetching credentials from node agent"

USER_CONFIG="${HOME}/.decloud/config"
NODE_CREDENTIALS="/etc/decloud/credentials"
APPSETTINGS=""

# Search for appsettings.Production.json in known locations
for candidate in \
    "/opt/decloud/DeCloud.NodeAgent/publish/appsettings.Production.json" \
    "/opt/decloud/publish/appsettings.Production.json" \
    "/opt/decloud/appsettings.Production.json"; do
    if [[ -f "$candidate" ]]; then
        APPSETTINGS="$candidate"
        break
    fi
done

fetch_credentials() {
    local orch_url="" api_key="" node_url="http://localhost:5100"

    # ── Orchestrator URL from appsettings ──────────────────────────────
    if [[ -n "$APPSETTINGS" ]]; then
        orch_url=$(grep -oP '"BaseUrl"\s*:\s*"\K[^"]+' "$APPSETTINGS" 2>/dev/null || true)
        [[ -n "$orch_url" ]] && log_ok "Orchestrator URL: ${orch_url}" \
                             || log_warn "Could not parse BaseUrl from ${APPSETTINGS}"
    else
        log_warn "appsettings.Production.json not found — DECLOUD_URL needs manual entry"
    fi

    # ── API key from /etc/decloud/credentials ──────────────────────────
    if [[ -f "$NODE_CREDENTIALS" ]]; then
        api_key=$(sudo grep -oP 'API_KEY=\K.+' "$NODE_CREDENTIALS" 2>/dev/null || true)
        [[ -n "$api_key" ]] && log_ok "API key loaded from ${NODE_CREDENTIALS}" \
                            || log_warn "API_KEY not found in ${NODE_CREDENTIALS}"
    else
        log_warn "${NODE_CREDENTIALS} not found — node may not be registered yet"
    fi

    # ── Write config file ──────────────────────────────────────────────
    mkdir -p "$(dirname "${USER_CONFIG}")"

    if [[ -f "${USER_CONFIG}" ]]; then
        # Preserve existing file — patch only keys we resolved
        [[ -n "$orch_url" ]] && sed -i "s|^DECLOUD_URL=.*|DECLOUD_URL=${orch_url}|" "${USER_CONFIG}"
        [[ -n "$api_key"  ]] && sed -i "s|^DECLOUD_TOKEN=.*|DECLOUD_TOKEN=${api_key}|" "${USER_CONFIG}"
        sed -i "s|^DECLOUD_NODE_URL=.*|DECLOUD_NODE_URL=${node_url}|" "${USER_CONFIG}"
        log_ok "Updated ${USER_CONFIG}"
    else
        cp "${DASHBOARD_DIR}/.env.example" "${USER_CONFIG}"
        [[ -n "$orch_url" ]] && sed -i "s|^DECLOUD_URL=.*|DECLOUD_URL=${orch_url}|" "${USER_CONFIG}"
        [[ -n "$api_key"  ]] && sed -i "s|^DECLOUD_TOKEN=.*|DECLOUD_TOKEN=${api_key}|" "${USER_CONFIG}"
        sed -i "s|^DECLOUD_NODE_URL=.*|DECLOUD_NODE_URL=${node_url}|" "${USER_CONFIG}"
        log_ok "Created ${USER_CONFIG}"
    fi

    chmod 600 "${USER_CONFIG}"

    # ── Warn on anything still missing ────────────────────────────────
    [[ -z "$orch_url" ]] && log_warn "DECLOUD_URL still needs manual entry in ${USER_CONFIG}"
    [[ -z "$api_key"  ]] && log_warn "DECLOUD_TOKEN still needs manual entry in ${USER_CONFIG}"
}

fetch_credentials

# ── done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Installation complete.${NC}"
echo ""
echo -e "  Launch:  ${CYAN}decloud dashboard${NC}"
echo -e "  Or:      ${CYAN}decloud-dashboard${NC}"
echo -e "  Or:      ${CYAN}decloud dashboard --node-only${NC}"
echo ""
echo -e "  Credentials: ${USER_CONFIG}  (chmod 600)"
echo ""