#!/usr/bin/env bash
# install-dashboard.sh — DeCloud CLI Dashboard installer (v2 redesign)
#
# What this does:
#   1. Checks Python 3.11+
#   2. Creates a virtualenv at ~/.decloud/dashboard-venv
#   3. Installs requirements.txt into the venv
#   4. Writes the launcher shim to /usr/local/bin/decloud-dashboard
#   5. Patches cli/decloud so 'decloud dashboard' forwards to the shim
#
# Run as the node operator user (not root). sudo is used only for
# writing to /usr/local/bin and for patching /usr/local/bin/decloud.
#
# Difference from the v1 installer:
#   • The launcher shim invokes the dashboard via its __main__.py path
#     directly (PYTHONPATH-clean). The previous shim used `python -m dashboard`
#     which only worked when invoked from a CWD whose contents included a
#     `dashboard/` directory — a CWD users almost never have.
#   • python-dotenv removed from requirements (redesign does not use it).

set -euo pipefail

# ── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log_step()  { echo -e "\n${CYAN}▶ ${BOLD}${1}${NC}"; }
log_ok()    { echo -e "  ${GREEN}✓${NC} ${1}"; }
log_warn()  { echo -e "  ${YELLOW}⚠${NC}  ${1}"; }
log_error() { echo -e "  ${RED}✗${NC} ${1}" >&2; }
log_info()  { echo -e "  ${1}"; }

# ── paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DASHBOARD_DIR="${SCRIPT_DIR}"
VENV_DIR="${HOME}/.decloud/dashboard-venv"
SHIM="/usr/local/bin/decloud-dashboard"
DECLOUD_BIN="/usr/local/bin/decloud"
USER_CONFIG="${HOME}/.decloud/config"
MIN_PYTHON_MINOR=11

# ── checks ────────────────────────────────────────────────────────────────────
log_step "Checking prerequisites"

check_python() {
    local py=""
    for candidate in python3 python3.12 python3.11; do
        if command -v "$candidate" &>/dev/null; then
            local minor major
            minor=$("$candidate" -c "import sys; print(sys.version_info.minor)")
            major=$("$candidate" -c "import sys; print(sys.version_info.major)")
            if [[ "$major" -eq 3 && "$minor" -ge "$MIN_PYTHON_MINOR" ]]; then
                py="$candidate"
                break
            fi
        fi
    done
    if [[ -z "$py" ]]; then
        log_error "Python 3.${MIN_PYTHON_MINOR}+ not found."
        log_info  "Install it: sudo apt install python3.11  (Ubuntu/Debian)"
        exit 1
    fi
    echo "$py"
}

PYTHON=$(check_python)
log_ok "Python: $($PYTHON --version)"

if [[ ! -f "${DASHBOARD_DIR}/requirements.txt" ]]; then
    log_error "requirements.txt not found at ${DASHBOARD_DIR}/requirements.txt"
    exit 1
fi
if [[ ! -f "${DASHBOARD_DIR}/__main__.py" ]]; then
    log_error "__main__.py not found at ${DASHBOARD_DIR}/__main__.py"
    exit 1
fi
log_ok "Dashboard source: ${DASHBOARD_DIR}"

# ── virtual environment ──────────────────────────────────────────────────────
log_step "Creating virtual environment at ${VENV_DIR}"

mkdir -p "$(dirname "$VENV_DIR")"
if [[ ! -d "${VENV_DIR}" ]]; then
    "$PYTHON" -m venv "${VENV_DIR}"
    log_ok "Venv created"
else
    log_ok "Venv already exists — reusing"
fi

# ── dependencies ─────────────────────────────────────────────────────────────
log_step "Installing Python dependencies"

"${VENV_DIR}/bin/pip" install --quiet --upgrade pip
"${VENV_DIR}/bin/pip" install --quiet -r "${DASHBOARD_DIR}/requirements.txt"
log_ok "Dependencies installed"

# ── launcher shim ────────────────────────────────────────────────────────────
log_step "Writing launcher shim → ${SHIM}"

# The shim invokes __main__.py directly so Python places DASHBOARD_DIR on
# sys.path automatically (the directory of the script being run is sys.path[0]).
# This makes `from config import cfg` etc. work regardless of the user's CWD.
sudo tee "${SHIM}" > /dev/null <<SHIM_EOF
#!/usr/bin/env bash
# DeCloud Dashboard launcher — auto-generated by install-dashboard.sh
# Do not edit; re-run install-dashboard.sh to update.
exec "${VENV_DIR}/bin/python" "${DASHBOARD_DIR}/__main__.py" "\$@"
SHIM_EOF

sudo chmod +x "${SHIM}"
log_ok "Shim written: ${SHIM}"

# ── patch cli/decloud ────────────────────────────────────────────────────────
log_step "Patching cli/decloud to add 'dashboard' subcommand"

patch_decloud() {
    local target="$1"
    if [[ ! -f "$target" ]]; then
        log_warn "cli/decloud not found at $target — skipping patch"
        return
    fi
    if grep -q '"dashboard"' "$target" 2>/dev/null; then
        log_ok "cli/decloud already has 'dashboard' subcommand — skipping"
        return
    fi

    sudo tee -a "$target" > /dev/null <<'PATCH_EOF'

# ── dashboard subcommand (added by install-dashboard.sh) ──────────────────────
if [[ "${1:-}" == "dashboard" ]]; then
    shift
    if ! command -v decloud-dashboard &>/dev/null; then
        echo "decloud-dashboard not installed."
        echo "Install it with: bash <repo>/cli/dashboard/install-dashboard.sh"
        exit 1
    fi
    exec decloud-dashboard "$@"
fi
PATCH_EOF

    log_ok "Patched $target"
}

if [[ -f "$DECLOUD_BIN" ]]; then
    patch_decloud "$DECLOUD_BIN"
else
    log_warn "$DECLOUD_BIN not found — 'decloud dashboard' wrapper not installed"
    log_info "You can still run the dashboard with: decloud-dashboard"
fi

# ── seed user config (if missing) ────────────────────────────────────────────
log_step "Configuring user config at ${USER_CONFIG}"

mkdir -p "$(dirname "${USER_CONFIG}")"
if [[ ! -f "${USER_CONFIG}" ]]; then
    cat > "${USER_CONFIG}" <<'CFG_EOF'
# DeCloud CLI Dashboard configuration.
# This file is mode 0600 — never share it.

# Local Node Agent (the most common case — works without auth).
DECLOUD_NODE_URL=http://localhost:5100

# Orchestrator (optional — enables the Earnings card on Overview).
# DECLOUD_URL=https://orchestrator.example.com
# DECLOUD_TOKEN=

# Refresh cadence in seconds (default: 5).
DECLOUD_REFRESH=5
CFG_EOF
    chmod 600 "${USER_CONFIG}"
    log_ok "Created ${USER_CONFIG}"
else
    chmod 600 "${USER_CONFIG}"
    log_ok "${USER_CONFIG} exists (permissions enforced 0600)"
fi

# ── done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}Installation complete.${NC}"
echo ""
echo -e "  Launch:  ${CYAN}decloud-dashboard${NC}"
[[ -f "$DECLOUD_BIN" ]] && \
    echo -e "  Or:      ${CYAN}decloud dashboard${NC}"
echo -e "  Or:      ${CYAN}decloud-dashboard --node-only${NC}"
echo ""
echo -e "  Config:  ${USER_CONFIG}  (chmod 600)"
echo ""
